tusen-ai/naive-ui

- demo/pages/docs/i18n/enUS/index.md
- demo/pages/docs/i18n/zhCN/index.md
- src/locales/common/itIT.ts
> fix(locales): fix Italiano locales

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/time-picker/demos/enUS/index.demo-entry.md
- src/time-picker/demos/zhCN/index.demo-entry.md
- src/time-picker/src/TimePicker.tsx
close [#2228](https://github.com/TuSimple/naive-ui/issues/2228)
> feat(time-picker): add `icon` slot

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tabs/src/TabPane.tsx
> fix: tab content inherit attrs

- src/table/demos/enUS/index.demo-entry.md
- src/table/demos/enUS/striped.demo.md
- src/table/demos/zhCN/index.demo-entry.md
https://github.com/TuSimple/naive-ui/blob/5efe8ae40d52b5fac5137d1bf7f86e1c009697fd/src/table/src/styles/index.cssr.ts#L89-L105
> docs(table): fix single-column and single-line description

- src/input/demos/zhCN/index.demo-entry.md
> docs: Input add event demo

- build/loaders/convert-md-to-doc.js
> fix: remove extra class

- src/_internal/select-menu/src/interface.ts
- src/drawer/src/interface.ts
- src/modal/src/interface.ts
- src/popover/src/interface.ts
> fix: esno run error

- demo/pages/docs/common-issues/zhCN/index.md
> docs: fix words in documents

- src/tooltip/tests/Tooltip.spec.ts
> test(tooltip): update test

- src/input/src/styles/input.cssr.ts
> fix(input): textarea white-space

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/color-picker/demos/enUS/disabled.demo.md
- src/color-picker/demos/enUS/index.demo-entry.md
- src/color-picker/demos/zhCN/disabled.demo.md
- src/color-picker/demos/zhCN/index.demo-entry.md
- src/color-picker/src/ColorPicker.tsx
- src/color-picker/src/ColorPickerTrigger.tsx
- src/color-picker/src/styles/index.cssr.ts
- src/form/demos/enUS/disabled.demo.md
- src/form/demos/zhCN/disabled.demo.md
> feat(ColorPicker): support disabled

- src/dialog/src/Dialog.tsx
> fix: Dialog console.log

- demo/pages/docs/usage-sfc/zhCN/index.md
- scripts/gen-component-declaration.js
> chore: update gen-component-declaration

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dynamic-input/src/DynamicInput.tsx
> fix: dynamic-input create button disabled when max is 0

- src/progress/demos/enUS/color.demo.md
- src/progress/demos/enUS/index.demo-entry.md
- src/progress/demos/enUS/multiple-circle.demo.md
- src/progress/demos/zhCN/color.demo.md
- src/progress/demos/zhCN/index.demo-entry.md
> docs: remove Chinese in enUS&inside-label for indicator-placement

- .gitignore
- src/back-top/demos/zhCN/index.demo-entry.md
> update doc and ignore file

- src/input/src/Input.tsx
> fix(type): input vm type

- .eslintrc.js
- src/select/tests/Select.spec.tsx
> workflow: eslint import/no-cycle validate

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/auto-complete/demos/enUS/index.demo-entry.md
- src/auto-complete/demos/zhCN/index.demo-entry.md
- src/auto-complete/src/AutoComplete.tsx
- src/cascader/demos/enUS/index.demo-entry.md
- src/cascader/demos/zhCN/index.demo-entry.md
- src/cascader/src/Cascader.tsx
- src/color-picker/demos/enUS/index.demo-entry.md
- src/color-picker/demos/zhCN/index.demo-entry.md
- src/color-picker/src/ColorPicker.tsx
- src/date-picker/demos/enUS/index.demo-entry.md
- src/date-picker/demos/zhCN/index.demo-entry.md
- src/date-picker/src/DatePicker.tsx
- src/mention/demos/enUS/index.demo-entry.md
- src/mention/demos/zhCN/index.demo-entry.md
- src/mention/src/Mention.tsx
- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/index.demo-entry.md
- src/slider/demos/enUS/index.demo-entry.md
- src/slider/demos/zhCN/index.demo-entry.md
- src/time-picker/demos/enUS/index.demo-entry.md
- src/time-picker/demos/zhCN/index.demo-entry.md
- src/time-picker/src/TimePicker.tsx
- src/tree-select/demos/enUS/index.demo-entry.md
- src/tree-select/demos/zhCN/index.demo-entry.md
> feat: component add placement prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/interface.ts
> fix: formItem and form validator rule type

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/TableParts/Body.tsx
> fix(data-table): fix scroll abnormal when used `virtual-scroll` and `expand` props

- src/tree/tests/Tree.spec.ts
> test(tree): update test

- demo/pages/docs/common-issues/enUS/index.md
- demo/pages/docs/community/enUS/index.md
- demo/pages/docs/customize-theme/enUS/index.md
- demo/pages/docs/fonts/enUS/index.md
- demo/pages/docs/i18n/enUS/index.md
- demo/pages/docs/import-on-demand/enUS/index.md
- demo/pages/docs/installation/enUS/index.md
- demo/pages/docs/introduction/enUS/index.md
- demo/pages/docs/jsx/enUS/index.md
- demo/pages/docs/style-position/enUS/index.md
- demo/pages/docs/supported-platforms/enUS/index.md
- demo/pages/docs/theme/enUS/index.demo-entry.md
- demo/pages/docs/theme/enUS/provide-theme.demo.md
- demo/pages/docs/theme/enUS/use-theme-vars.demo.md
- demo/pages/docs/usage-sfc/enUS/index.md
> Docs fixes

- src/config-provider/src/interface.ts
- src/themes/dark.ts
- src/themes/light.ts
> feat(themes): add icon-wrapper

- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/index.demo-entry.md
> Docs: Adjust n-select `render-tag`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/locales/common/deDE.ts
Add missing translations.
Adjust date formats.
> fix: i18n adjust deDE locale

- src/_utils/vue/resolve-slot.ts
> fix(_utils): optimize code

- src/icon/demos/enUS/index.demo-entry.md
- src/icon/demos/zhCN/index.demo-entry.md
> docs: fix version

- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/zhCN/index.demo-entry.md
- src/loading-bar/demos/enUS/index.demo-entry.md
- src/loading-bar/demos/zhCN/index.demo-entry.md
- src/notification/demos/enUS/index.demo-entry.md
- src/notification/demos/zhCN/index.demo-entry.md
> docs: fix bug when markdown in title

- src/mention/demos/zhCN/index.demo-entry.md
> docs(mention): Update mention docs.

- src/dropdown/demos/zhCN/index.demo-entry.md
> docs(dropdown): Update dropdown docs.

- src/number-animation/tests/NumericAnimation.spec.ts
> test(number-animation): add test

- src/locales/common/eo.ts
Hi, I'd like to add Esperanto language support to this library.
> Added Esperanto locale

- src/locales/date/eo.ts
Hi, I'd like to add Esperanto language support to this library.
> Added Esperanto date locale

- scripts/release-changelog.js
> chore: changelog use markdown in DingTalk

- src/number-animation/tests/NumericAnimation.spec.ts
> test(number-animation): update test

- src/number-animation/tests/NumericAnimation.spec.ts
- src/watermark/demos/enUS/index.demo-entry.md
- src/watermark/demos/zhCN/index.demo-entry.md
- src/watermark/tests/Watermark.spec.ts
> docs(watermark): update docs

- src/popover/src/PopoverBody.tsx
> feat(popover): inlineThemeDisabled

- src/color-picker/src/ColorPicker.tsx
> feat(color-picker): inlineThemeDisabled

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/table/src/styles/index.cssr.ts
> fix(table): fix `border-color` transition bug

- src/radio/demos/enUS/index.demo-entry.md
- src/radio/demos/zhCN/index.demo-entry.md
> docs: update radio docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- demo/pages/docs/i18n/enUS/index.md
- demo/pages/docs/i18n/zhCN/index.md
- src/locales/common/skSK.ts
- src/locales/index.spec.tsx
@07akioni 合并之后更新一下测试，我本地因为未知原因无法更新 snapshot
> fix(locales): Perfect Slovak locales

- .github/workflows/issue-add-bug.yml
- .github/workflows/issue-add-label.yml
- .github/workflows/issue-open-check.yml
- .github/workflows/issue-reply.yml
- .github/workflows/node.js.yml
- .github/workflows/sync-gitee.yml
> chore(ci): update actions version

- src/checkbox/demos/enUS/index.demo-entry.md
- src/checkbox/demos/enUS/size.demo.vue
- src/checkbox/demos/zhCN/index.demo-entry.md
- src/checkbox/demos/zhCN/size.demo.vue
- src/checkbox/src/Checkbox.tsx
> feat(checkbox): add docs & inlineThemeDisabled

- src/collapse/src/Collapse.tsx
> feat(collapse): inlineThemeDisabled

- src/loading-bar/demos/enUS/basic.demo.vue
- src/loading-bar/demos/enUS/index.demo-entry.md
- src/loading-bar/demos/zhCN/basic.demo.vue
- src/loading-bar/demos/zhCN/index.demo-entry.md
> docs(loading-bar): md to vue

- src/rate/src/Rate.tsx
> feat(rate): add inlineThemeDisabled

- src/tree/src/Tree.tsx
- src/tree/tests/Tree.spec.ts
related: https://github.com/TuSimple/naive-ui/issues/1767
> fix(tree): default-expand-all should works with dynamic data

- src/statistic/tests/Statistic.spec.ts
> test(statistic): add test case

- src/countdown/src/Countdown.tsx
- src/countdown/tests/Countdown.spec.ts
> test(countdown): add test case

- src/rate/src/Rate.tsx
> fix(rate): fix themeClassHandle

- src/page-header/src/PageHeader.tsx
> feat(page-header): add inlineThemeDisabled

- src/empty/src/Empty.tsx
> feat(empty): disable inline theme

- src/result/src/Result.tsx
> feat(result): add inlineThemeDisabled

- src/descriptions/src/Descriptions.tsx
> feat(descriptions): disable inline theme

- src/code/src/Code.tsx
> feat(code): disable inlneTheme

- src/log/src/Log.tsx
> feat(log): add inlineThemeDisabled

- src/dynamic-tags/src/DynamicTags.tsx
> feat(dynamic-tags): disable inline theme

- src/dynamic-input/src/DynamicInput.tsx
> feat(dynamic-input): add inlineThemeDisabled

- src/mention/src/Mention.tsx
> feat(mention): add inlineThemeDisabled

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popover/demos/enUS/index.demo-entry.md
- src/popover/demos/zhCN/center-arrow-debug.demo.vue
- src/popover/demos/zhCN/index.demo-entry.md
- src/popover/src/PopoverBody.tsx
- src/popover/src/styles/index.cssr.ts
> feat(popover): adds `arrow-point-to-center` prop

- src/date-picker/src/DatePicker.tsx
- src/date-picker/src/panel/date.tsx
- src/date-picker/src/panel/daterange.tsx
- src/date-picker/src/panel/datetime.tsx
- src/date-picker/src/panel/datetimerange.tsx
- src/date-picker/src/panel/month.tsx
- src/date-picker/src/panel/use-panel-common.ts
> feat(date-picker): add inlineThemeDisabled

- src/data-table/demos/enUS/summary.demo.md
- src/data-table/demos/zhCN/summary.demo.md
> docs(data-table): use Vnode

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/collapse/demos/zhCN/index.demo-entry.md
- src/collapse/demos/zhCN/rtl-debug.demo.vue
- src/collapse/src/Collapse.tsx
- src/collapse/src/CollapseItem.tsx
- src/collapse/src/styles/rtl.cssr.ts
- src/collapse/styles/index.ts
- src/collapse/styles/rtl.ts
- src/styles.ts
> feat(collapse): support rtl

- src/list/src/List.tsx
> feat(list): add inlineThemeDisabled

- src/collapse-transition/src/CollapseTransition.tsx
> feat(collapse-transition): add inlineThemeDisabled

- src/loading-bar/src/LoadingBar.tsx
> feat(loading-bar): add inlineThemeDisabled

- src/upload/src/Upload.tsx
> feat(upload): disable inlne theme

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/message/demos/enUS/index.demo-entry.md
- src/message/demos/enUS/no-icon.demo.vue
- src/message/demos/zhCN/index.demo-entry.md
- src/message/demos/zhCN/no-icon.demo.vue
- src/message/src/Message.tsx
- src/message/src/MessageEnvironment.tsx
- src/message/src/MessageProvider.tsx
- src/message/src/message-props.ts
- src/message/src/types.ts
- src/message/tests/Message.spec.tsx
ref https://github.com/TuSimple/naive-ui/issues/2495
> Feat(message) add show icon prop

- src/time-picker/src/TimePicker.tsx
> feat(time-picker): add inlineThemeDisabled

- src/config-provider/demos/enUS/inline-theme-disabled.demo.vue
> docs(config-provider): inline-theme-disabled description

- src/button/demos/enUS/basic.demo.vue
- src/button/demos/enUS/index.demo-entry.md
- src/button/demos/zhCN/basic.demo.vue
- src/button/demos/zhCN/index.demo-entry.md
> docs: update button docs

- src/config-provider/demos/enUS/index.demo-entry.md
- src/config-provider/demos/zhCN/index.demo-entry.md
> docs(config-provider): Update date-locale parameter description.

- src/dynamic-input/tests/DynamicInput.spec.ts
> test(dynamic-input): add test

- src/steps/tests/Steps.spec.ts
> test(steps): Step `icon` slot

- src/timeline/tests/Timeline.spec.ts
> test(timeline): test `lineType` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dynamic-tags/demos/zhCN/slot.demo.vue
- src/dynamic-tags/src/DynamicTags.tsx
> feat(dynamic-tag): handle blur

- src/_internal/select-menu/src/SelectMenu.tsx
> feat(select): optimize code

- src/dynamic-input/tests/DynamicInput.spec.ts
> test(dynamic-input): add test and optimize test

- scripts/gen-component-declaration.js
- volar.d.ts
> type: remove NxButtin componnet

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/loading/src/styles/index.cssr.ts
> fix(base-loading): wrong position

- CONTRIBUTING.md
> docs: update contribute md

- .gitignore
- src/space/demos/zhCN/index.demo-entry.md
> docs(space): modify description for size prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/index.ts
> type: fix data-table type

- src/pagination/demos/enUS/index.demo-entry.md
- src/pagination/demos/zhCN/index.demo-entry.md
> docs(pagination): add undocumented disabled prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/cascader/demos/enUS/index.demo-entry.md
- src/cascader/demos/zhCN/index.demo-entry.md
- src/cascader/src/Cascader.tsx
> feat(cascader): add `menu-props` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree-select/demos/enUS/async.demo.vue
- src/tree-select/demos/enUS/index.demo-entry.md
- src/tree-select/demos/zhCN/async.demo.vue
- src/tree-select/demos/zhCN/index.demo-entry.md
- src/tree-select/index.ts
- src/tree-select/src/TreeSelect.tsx
- src/tree-select/src/interface.ts
> feat(tree-select): add async loading

- README.zh-CN.md
> docs(README): 添加钉钉群加入方法

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/TableParts/Body.tsx
> fix(data-table): Fix row disorder when using `expand` type

- src/carousel/tests/Carousel.spec.tsx
> chore(ci): fix error

- src/dynamic-tags/tests/DynamicTags.spec.ts
> test(dynamic-tags): add test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/demos/enUS/index.demo-entry.md
- src/input/demos/enUS/password.demo.vue
- src/input/src/Input.tsx
This first time to make PR to this projects. Sorry if I do anything wrong.
ps. you can change props name to another that you thinks it meaningful😊
> feat(input): add ability to custom password toggle icon

- src/card/tests/Card.spec.ts
> test(card): add test

- src/carousel/tests/Carousel.spec.tsx
> test(carousel): add test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/drawer/demos/enUS/index.demo-entry.md
- src/drawer/demos/zhCN/index.demo-entry.md
- src/drawer/src/Drawer.tsx
- src/drawer/src/DrawerBodyWrapper.tsx
> feat: drawer add onAfterLeave and onAfterEnter props

- src/icon-wrapper/tests/IconWrapper.spec.ts
- src/icon-wrapper/tests/server.spec.tsx
> test(icon-wrapper): add test

- src/icon/demos/enUS/index.demo-entry.md
- src/icon/demos/zhCN/index.demo-entry.md
> docs(icon-wrapper): fix props docs

- src/page-header/tests/PageHeader.spec.tsx
> test(page-header): add test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/radio/demos/enUS/group.demo.vue
- src/radio/demos/enUS/index.demo-entry.md
- src/radio/src/Radio.tsx
- src/radio/src/use-radio.ts
- src/radio/tests/Radio.spec.ts
Closes [#2707](https://github.com/TuSimple/naive-ui/issues/2707)
> feat(radio): add radio label

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/calendar/src/Calendar.tsx
- src/calendar/src/styles/index.cssr.ts
> fix(calendar): disabled cells are clickable

- src/popconfirm/demos/enUS/index.demo-entry.md
- src/popconfirm/demos/zhCN/index.demo-entry.md
- src/popconfirm/src/Popconfirm.ts
- src/popconfirm/src/PopconfirmPanel.tsx
> fix(popconfirm): type declaration

- src/watermark/tests/Watermark.spec.ts
> test(watermark): add test

- src/auto-complete/src/AutoComplete.tsx
- src/cascader/src/CascaderMenu.tsx
- src/cascader/src/CascaderSelectMenu.tsx
- src/date-picker/src/DatePicker.tsx
- src/date-picker/src/panel/panelHeader.tsx
- src/modal/src/BodyWrapper.tsx
- src/popover/src/PopoverBody.tsx
- src/select/src/Select.tsx
- src/time-picker/src/TimePicker.tsx
- src/tree-select/src/TreeSelect.tsx
> refactor: enhance type

- src/auto-complete/tests/AutoComplete.spec.ts
> test(auto-complete): add test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/demos/enUS/custom-icon.demo.vue
- src/input-number/demos/enUS/index.demo-entry.md
- src/input-number/demos/zhCN/custom-icon.demo.vue
- src/input-number/demos/zhCN/index.demo-entry.md
- src/input-number/src/InputNumber.tsx
- src/input/src/styles/input.cssr.ts
> feat(input-number): adds `add-icon` and `minus-icon` slots

- src/cascader/tests/Cascader.spec.ts
> test(cascader): add test

- demo/pages/docs/i18n/enUS/index.md
- demo/pages/docs/i18n/zhCN/index.md
- src/locales/__snapshots__/index.spec.tsx.snap
> feat(locales): optimize code

- src/color-picker/tests/ColorPicker.spec.tsx
> test(color-picker): add test

- src/data-table/demos/enUS/controlled-filter.demo.vue
- src/data-table/demos/enUS/controlled-page.demo.md
- src/data-table/demos/enUS/controlled-sorter.demo.md
- src/data-table/demos/enUS/custom-select.demo.md
- src/data-table/demos/enUS/custom-style.demo.md
- src/data-table/demos/enUS/ellipsis-tooltip.demo.md
- src/data-table/demos/enUS/ellipsis.demo.md
- src/data-table/demos/enUS/fixed-header-column.demo.md
- src/data-table/demos/enUS/fixed-header.demo.md
- src/data-table/demos/enUS/flex-height.demo.md
- src/data-table/demos/enUS/multiple-sorter.demo.md
- src/data-table/demos/enUS/render-header.demo.md
- src/data-table/demos/enUS/select.demo.md
- src/data-table/demos/enUS/virtual.demo.md
- src/data-table/demos/zhCN/controlled-filter.demo.vue
- src/data-table/demos/zhCN/controlled-page.demo.md
- src/data-table/demos/zhCN/controlled-sorter.demo.md
- src/data-table/demos/zhCN/custom-select.demo.md
- src/data-table/demos/zhCN/custom-style.demo.md
- src/data-table/demos/zhCN/ellipsis-tooltip.demo.md
- src/data-table/demos/zhCN/ellipsis.demo.md
- src/data-table/demos/zhCN/fixed-header-column.demo.md
- src/data-table/demos/zhCN/fixed-header.demo.md
- src/data-table/demos/zhCN/flex-height.demo.md
- src/data-table/demos/zhCN/height-debug.demo.md
- src/data-table/demos/zhCN/multiple-sorter.demo.md
- src/data-table/demos/zhCN/render-header.demo.md
- src/data-table/demos/zhCN/select.demo.md
- src/data-table/demos/zhCN/virtual.demo.md
> docs: update datatable docs

- src/button/tests/Button.spec.tsx
> feat(button): optimize code

- src/dynamic-tags/demos/enUS/index.demo-entry.md
- src/dynamic-tags/demos/zhCN/index.demo-entry.md
> docs(dynamic-tags): on-update:value type

- src/carousel/tests/Carousel.spec.tsx
> test(carousel): optimize code

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/date-picker/src/DatePicker.tsx
> fix(date-picker): `actions` can not be `null`

- src/date-picker/demos/enUS/daterange.demo.vue
- src/date-picker/demos/enUS/datetimerange.demo.vue
- src/date-picker/demos/enUS/default-time.demo.vue
- src/date-picker/demos/enUS/disabled-time.demo.vue
- src/date-picker/demos/zhCN/daterange.demo.vue
- src/date-picker/demos/zhCN/datetimerange.demo.vue
- src/date-picker/demos/zhCN/default-time.demo.vue
- src/date-picker/demos/zhCN/disabled-time.demo.vue
Signed-off-by: Sepush [sepush@outlook.com](mailto:sepush@outlook.com)
> docs(date-picker): type of demo 

- src/date-picker/tests/DatePicker.spec.tsx
> test(date-picker): add test

- src/icon/tests/Icon.spec.ts
> test(icon): add test

- src/input/tests/Input.spec.tsx
> test(input): add test

- src/input/tests/Input.spec.tsx
> feat(input): optimize code

- src/input-number/tests/InputNumber.spec.tsx
> test(input-number): add test

- src/space/src/Space.tsx
> Add space-evenly to n-space component

- .github/workflows/node.js.yml
> fix(ci): pnpm install

- src/_internal/selection/src/Selection.tsx
- src/_internal/selection/src/styles/index.cssr.ts
fix：when there is too much data, the floating frame is not displayed completely. ([#2815](https://github.com/TuSimple/naive-ui/issues/2815))
> fix(selection): add scroll bar

- src/data-table/src/interface.ts
- src/data-table/src/utils.ts
fix #1813
我试了一下，手动传入minWidth是有效的
> fix(data-table): add minWidth to Column

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/zhCN/index.demo-entry.md
- src/dialog/src/DialogEnvironment.tsx
> feat(dialog): `useDialog` supports `autoFocus` option

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/time-picker/demos/enUS/confirm.demo.vue
- src/time-picker/demos/enUS/index.demo-entry.md
- src/time-picker/demos/zhCN/confirm.demo.vue
- src/time-picker/demos/zhCN/index.demo-entry.md
- src/time-picker/src/Panel.tsx
- src/time-picker/src/TimePicker.tsx
> feat(time-picker): add `on-confirm` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/date-picker/demos/enUS/events.demo.vue
- src/date-picker/demos/enUS/index.demo-entry.md
- src/date-picker/demos/zhCN/events.demo.vue
- src/date-picker/demos/zhCN/index.demo-entry.md
- src/date-picker/src/DatePicker.tsx
- src/date-picker/src/panel/use-calendar.ts
- src/date-picker/src/panel/use-panel-common.ts
> feat(date-picker): add `on-clear` and `on-confirm` props

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree-select/demos/enUS/index.demo-entry.md
- src/tree-select/demos/zhCN/debug.demo.vue
- src/tree-select/demos/zhCN/index.demo-entry.md
- src/tree-select/src/TreeSelect.tsx
> feat(tree-select): add `loading` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/drawer/demos/enUS/index.demo-entry.md
- src/drawer/demos/zhCN/index.demo-entry.md
- src/drawer/src/Drawer.tsx
- src/drawer/src/DrawerBodyWrapper.tsx
> feat(drawer): add `show-mask` props

- src/layout/tests/Layout.spec.ts
> test(layout): add test

- src/layout/tests/Layout.spec.ts
> test(layout): optimize code

- src/form/demos/enUS/custom-messages.demo.vue
- src/form/demos/zhCN/custom-messages.demo.vue
> docs(form): fix custom-message.demo, closes #2922

- src/space/tests/Space.spec.tsx
- src/space/tests/__snapshots__/Space.spec.tsx.snap
> test(space): add test

- src/countdown/index.ts
- src/countdown/src/Countdown.tsx
> fix: export the CountdownTimeInfo interface

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/watermark/src/Watermark.tsx
> fix(watermark): clsPreifx not working

- src/collapse-transition/tests/CollapseTransition.spec.tsx
> test(collapse-transition): add test

- src/menu/src/styles/index.cssr.ts
> fix: menu-item--selected::before not working

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/demos/enUS/index.demo-entry.md
- src/form/demos/enUS/render-feedback.demo.vue
- src/form/demos/zhCN/index.demo-entry.md
- src/form/demos/zhCN/render-feedback.demo.vue
- src/form/src/Feedbacks.tsx
- src/form/src/FormItem.tsx
- src/form/src/context.ts
[#2525](https://github.com/TuSimple/naive-ui/issues/2525)
> feat(formItem): add `render-feedback` prop

- src/form/demos/enUS/dynamic.demo.vue
- src/form/demos/enUS/index.demo-entry.md
- src/form/demos/zhCN/dynamic.demo.vue
- src/form/demos/zhCN/index.demo-entry.md
> docs(form): add dynamic form demo #2810

- src/dropdown/demos/zhCN/size.demo.vue
> update size attribute value

- src/scrollbar/tests/Scrollbar.spec.ts
> test(scrollbar): add test

- src/upload/demos/enUS/index.demo-entry.md
> doc: fix drag to upload demo link

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/image/src/Image.tsx
- src/image/src/ImageGroup.tsx
> fix(image): switch pictures doesn't work in SSR mode

- CHANGELOG.zh-CN.md
> feat: optimized code

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
- src/tree/src/Tree.tsx
- src/tree/src/TreeNode.tsx
- src/tree/src/interface.ts
Add expandOnClick props in n-tree. closes [#2949](https://github.com/TuSimple/naive-ui/issues/2949).
> feat: add expandOnClick props in n-tree

- src/affix/tests/Affix.spec.ts
> test(affix): optimize test

- src/dialog/demos/enUS/index.demo-entry.md
> docs: fix table display incorrectly

- src/upload/src/utils.ts
> fix: make `createImageDataUrl` more memory efficient

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/upload/demos/enUS/drag.demo.vue
- src/upload/demos/zhCN/drag.demo.vue
- src/upload/src/UploadDragger.tsx
> feat: disable dragger when maximum number of files was reached

- demo/pages/docs/ssr/enUS/index.md
- demo/pages/docs/ssr/zhCN/index.md
> docs: fix nuxt config

- src/input/src/styles/input-group-label.cssr.ts
> fix(input group label): fix input group label text cut off

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/back-top/src/BackTop.tsx
> fix(back-top): fix `n-back-top` has log warnings of console when use `show` prop

- src/pagination/demos/enUS/quick-jumper.demo.vue
- src/pagination/demos/zhCN/quick-jumper.demo.vue
> chore: add quick jumper tips

- src/grid/src/Grid.tsx
- src/grid/src/GridItem.tsx
- src/grid/tests/Grid.spec.tsx
> fix(grid): hydrate incorrectly

- src/tree/tests/Tree.spec.ts
> test(tree): add test

- README.zh-CN.md
> fix: fix README.zh-CN.md link

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/select/src/Select.tsx
> fix(select): filter prop invalid, closes #3175

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tabs/src/Tabs.tsx
> fix(tabs): fix `n-tabs`'s `bar-width` props invalid when `0` set

- src/button/src/styles/index.cssr.ts
修复button组件icon位置显示异常的问题（icon相对button过大或过小时会触发）
> fix(button): style

- src/code/demos/zhCN/index.demo-entry.md
> cn-docs-fix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_utils/env/is-native-lazy-load.ts
- src/avatar/demos/enUS/index.demo-entry.md
- src/avatar/demos/enUS/lazy.demo.vue
- src/avatar/demos/zhCN/index.demo-entry.md
- src/avatar/demos/zhCN/lazy.demo.vue
- src/avatar/src/Avatar.tsx
- src/avatar/src/styles/index.cssr.ts
- src/image/src/Image.tsx
> feat: avatar lazyload

- src/message/demos/enUS/index.demo-entry.md
- src/message/demos/zhCN/index.demo-entry.md
> docs(message): fix MessageProvider's create props description

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/number-animation/demos/enUS/finish.demo.vue
- src/number-animation/demos/enUS/index.demo-entry.md
- src/number-animation/demos/zhCN/finish.demo.vue
- src/number-animation/demos/zhCN/index.demo-entry.md
- src/number-animation/src/NumberAnimation.tsx
> Add `on-finish` prop for `n-number-animation`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/enUS/select-single.demo.vue
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/demos/zhCN/select-single.demo.vue
- src/data-table/src/TableParts/Body.tsx
- src/data-table/src/TableParts/BodyRadio.tsx
- src/data-table/src/TableParts/Header.tsx
- src/data-table/src/interface.ts
- src/data-table/src/use-check.ts
- src/data-table/tests/DataTable.spec.tsx
> feat(datatable): add `single` prop to datatable #3056

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_styles/common/dark.ts
- src/_styles/common/light.ts
- src/drawer/demos/enUS/adjustable.demo.vue
- src/drawer/demos/enUS/index.demo-entry.md
- src/drawer/demos/zhCN/adjustable.demo.vue
- src/drawer/demos/zhCN/index.demo-entry.md
- src/drawer/src/Drawer.tsx
- src/drawer/src/DrawerBodyWrapper.tsx
- src/drawer/src/interface.ts
- src/drawer/src/styles/index.cssr.ts
- src/drawer/styles/light.ts
- src/drawer/tests/Drawer.spec.tsx
> feat(drawer): add a new prop(adjustable) so that the drawer can adjust its width/height

- src/countdown/tests/Countdown.spec.ts
> test(countdown): add test

- package.json
- vite.config.js
> chore: upgrade to vite3.0.0

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/notification/demos/enUS/index.demo-entry.md
- src/notification/demos/enUS/type.demo.vue
- src/notification/demos/zhCN/index.demo-entry.md
- src/notification/demos/zhCN/type.demo.vue
- src/notification/src/Notification.tsx
- src/notification/src/NotificationEnvironment.tsx
- src/notification/src/NotificationProvider.tsx
> feat(notification): add `keepAliveOnHover` prop

- CHANGELOG.zh-CN.md
> feat(changelog): fix error

- CONTRIBUTING.md
> chore(contributing): add notes

- demo/pages/docs/import-on-demand/enUS/index.md
- demo/pages/docs/import-on-demand/zhCN/index.md
Add the `unplugin-auto-import` plugin to automatically import API.
> Add the `unplugin-auto-import` plugin to automatically import API.

- src/affix/demos/enUS/basic.demo.vue
- src/affix/demos/enUS/position.demo.vue
- src/affix/demos/zhCN/basic.demo.vue
- src/affix/demos/zhCN/position.demo.vue
- src/back-top/demos/enUS/target-container-selector.demo.vue
- src/back-top/demos/zhCN/target-container-selector.demo.vue
> chore: Simplifying type declarations

- src/data-table/demos/enUS/index.demo-entry.md
- src/popconfirm/demos/enUS/index.demo-entry.md
- src/popconfirm/demos/zhCN/index.demo-entry.md
> docs(popconfirm): link methods to popover

- src/data-table/demos/enUS/index.demo-entry.md
- src/form/demos/enUS/disabled.demo.vue
- src/form/demos/zhCN/disabled.demo.vue
> docs(form): fix some model binding issues in disabled axample

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/src/InputNumber.tsx
> fix(input-button): register mouseup event multiple times when hold

- demo/store/menu-options.js
> chore: move lagacy-grid to legacy menu-options

- src/locales/common/deDE.ts
> fix(de-DE): add missing translations

- src/carousel/src/Carousel.tsx
> fix(n-carousel): fix can not fix translate after dragging

- src/carousel/src/Carousel.tsx
> fix(n-carousel): fix sequence layout carousel translate

- src/dialog/demos/enUS/mask.demo.vue
- src/dialog/demos/zhCN/mask.demo.vue
- src/dialog/src/DialogEnvironment.tsx
> feat: finish `on-esc`

- .github/workflows/issue-reply.yml
> chore(github): optimize usage label

- src/dialog/demos/enUS/index.demo-entry.md
> docs(dialog): fix props table

- src/dialog/demos/enUS/index.demo-entry.md
> docs(dialog): optimize docs

- src/auto-complete/demos/enUS/index.demo-entry.md
- src/cascader/demos/enUS/index.demo-entry.md
- src/cascader/demos/zhCN/index.demo-entry.md
- src/dialog/demos/enUS/index.demo-entry.md
- src/dropdown/demos/enUS/index.demo-entry.md
- src/dropdown/demos/zhCN/index.demo-entry.md
> docs: fix some minor issues

- README.zh-CN.md
> update readme contributing link

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/demos/zhCN/debug.demo.vue
- src/menu/demos/zhCN/index.demo-entry.md
- src/menu/src/Submenu.tsx
> fix(menu): extra not work with submenu

- demo/utils/EditInCodeSandboxButton.vue
> fix(site): pass correct code language to codesandbox

- src/transfer/demos/enUS/index.demo-entry.md
- src/transfer/demos/zhCN/index.demo-entry.md
> docs(transfer): update props docs

- demo/utils/codesandbox.js
> chore(codesandbox): fix error

- src/tree/demos/zhCN/index.demo-entry.md
> docs(tree): api去除多余右括号

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dropdown/src/styles/index.cssr.ts
> fix(dropdown): option prefix & suffix's z-index, closes #3433

- src/upload/demos/enUS/index.demo-entry.md
- src/upload/demos/zhCN/index.demo-entry.md
> docs(upload): id caveat

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/src/InputNumber.tsx
- src/tree/src/Tree.tsx
> fix(input-number):  peers theme can't be configured, closes #3422

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
- src/tree/src/Tree.tsx
- src/tree/src/keyboard.tsx
> feat(tree): adds `keyboard` prop, closes #3438

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/collapse/demos/enUS/disabled.demo.vue
- src/collapse/demos/enUS/index.demo-entry.md
- src/collapse/demos/zhCN/disabled.demo.vue
- src/collapse/demos/zhCN/index.demo-entry.md
- src/collapse/src/Collapse.tsx
- src/collapse/src/CollapseItem.tsx
- src/collapse/src/styles/index.cssr.ts
- src/collapse/styles/light.ts
> feat(collapse-item): adds `disabled` prop, closes #3408

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/transfer/demos/zhCN/asynchronous-options-debug.demo.vue
- src/transfer/demos/zhCN/index.demo-entry.md
- src/transfer/src/TransferList.tsx
- src/transfer/src/use-transfer-data.ts
> fix(transfer): fix error when passing asynchronous options

- src/transfer/src/use-transfer-data.ts
> perf(transfer): option filter

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/pagination/demos/enUS/index.demo-entry.md
- src/pagination/demos/enUS/quick-jumper.demo.vue
- src/pagination/demos/zhCN/index.demo-entry.md
- src/pagination/demos/zhCN/quick-jumper.demo.vue
- src/pagination/src/Pagination.tsx
> feat(pagination): add `trigger-quick-jump-on` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/pagination/demos/enUS/index.demo-entry.md
- src/pagination/demos/enUS/quick-jumper.demo.vue
- src/pagination/demos/zhCN/index.demo-entry.md
- src/pagination/demos/zhCN/quick-jumper.demo.vue
- src/pagination/src/Pagination.tsx
> refactor(input-number): quick jump

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- package.json
- src/_internal/scrollbar/src/Scrollbar.tsx
- src/auto-complete/src/AutoComplete.tsx
- src/carousel/src/Carousel.tsx
- src/cascader/src/Cascader.tsx
- src/color-picker/src/ColorPicker.tsx
- src/data-table/src/TableParts/SelectionMenu.tsx
- src/date-picker/src/DatePicker.tsx
- src/date-picker/src/panel/panelHeader.tsx
- src/modal/src/Modal.tsx
- src/popover/src/PopoverBody.tsx
- src/select/src/Select.tsx
- src/time-picker/src/TimePicker.tsx
- src/tree-select/src/TreeSelect.tsx
- src/version.ts
> fix: some components works abnormally in open mode shadow DOM, closes #3281

- src/pagination/demos/enUS/page-size-option.demo.vue
- src/pagination/demos/zhCN/page-size-option.demo.vue
> docs:  pagination文档修改

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/src/utils.tsx
> fix(menu): type

- src/_mixins/use-theme.ts
- src/message/demos/zhCN/rtl-debug.demo.vue
- src/message/src/Message.tsx
- src/message/src/styles/rtl.cssr.ts
> refactor(message): rtl

- src/transfer/tests/Transfer.spec.ts
> test(transfer): add test

- src/input/demos/enUS/index.demo-entry.md
- src/input/demos/enUS/size.demo.vue
- src/input/demos/zhCN/index.demo-entry.md
- src/input/demos/zhCN/size.demo.vue
> docs(n-input): add missing size `tiny` docs

- src/card/demos/enUS/index.demo-entry.md
- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/enUS/size.demo.vue
- src/select/demos/zhCN/index.demo-entry.md
- src/select/demos/zhCN/size.demo.vue
additionally fixed small issue in card docs
> docs(n-select): add `tiny` to prop `size`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tag/src/styles/index.cssr.ts
> fix(tag): pointer should be not allow when disabled

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree-select/demos/enUS/index.demo-entry.md
- src/tree-select/demos/zhCN/index.demo-entry.md
- src/tree-select/src/TreeSelect.tsx
- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
- src/tree/src/Tree.tsx
> feat(tree): add disabled-field prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/demos/zhCN/index.demo-entry.md
- src/input/demos/zhCN/textarea-resize-debug.demo.vue
- src/input/src/Input.tsx
> Fix textarea resize

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/countdown/src/Countdown.tsx
> fix(countdown): fix error when using `reset` method in `onFinish` callback

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/statistic/src/Statistic.tsx
- src/statistic/src/styles/index.cssr.ts
- src/statistic/styles/light.ts
> feat(statistic): add `valueFontSize` theme var

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/demos/enUS/index.demo-entry.md
- src/menu/demos/zhCN/index.demo-entry.md
- src/menu/src/Menu.tsx
> feat(menu): add `disabledField` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/radio/demos/enUS/index.demo-entry.md
- src/radio/demos/zhCN/index.demo-entry.md
- src/radio/src/RadioGroup.tsx
- src/radio/src/interface.ts
- src/radio/src/use-radio.ts
> fix(radio): fix warning when value prop type is boolean

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/demos/enUS/index.demo-entry.md
- src/slider/demos/enUS/keyboard.demo.vue
- src/slider/demos/zhCN/index.demo-entry.md
- src/slider/demos/zhCN/keyboard.demo.vue
- src/slider/src/Slider.tsx
> feat(slider): add `keyboard` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> fix: word error

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/rate/demos/enUS/clearable.demo.vue
- src/rate/demos/enUS/index.demo-entry.md
- src/rate/demos/zhCN/clearable.demo.vue
- src/rate/demos/zhCN/index.demo-entry.md
- src/rate/src/Rate.tsx
- src/rate/tests/Rate.spec.ts
> feat(rate): add clearable prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> Move NRadio warning fix in NEXT_VERSION > Fixes

- src/countdown/src/Countdown.tsx
`rafId` will always be `null`
```ts
if (rafId !== null) {
window.cancelAnimationFrame(rafId)
rafId = null
}
```
will never reach
> chore(countdown): remove dead code

- src/data-table/demos/enUS/border.demo.vue
- src/data-table/demos/zhCN/border.demo.vue
> docs(data-table): adjust border.demo.vue

- src/form/src/FormItem.tsx
- src/form/src/styles/form-item.cssr.ts
> fix(form-item): left label style

- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/zhCN/index.demo-entry.md
> docs(dialog): fix options table

- src/transfer/tests/Transfer.spec.ts
> chore: fix ci test error

- src/switch/demos/enUS/index.demo-entry.md
- src/switch/demos/zhCN/index.demo-entry.md
> docs(switch): fix props table

- src/radio/styles/dark.ts
> fix(radio): fix dark theme style error

- src/upload/src/interface.ts
> fix(upload): onBeforeUpload type error

- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/index.demo-entry.md
> docs(select): fix prop table

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dynamic-tags/index.ts
> feat(dynamic-tags): export `DynamicTagsOption` type

- src/menu/demos/enUS/index.demo-entry.md
- src/menu/demos/zhCN/index.demo-entry.md
> docs: menu文件修复

- README.md
- README.zh-CN.md
> chore: update readme

- .github/workflows/issue-reply.yml
- demo/pages/docs/introduction/enUS/index.md
- demo/pages/docs/introduction/zhCN/index.md
- demo/pages/home/Footer.vue
> chore: update community

- src/icon/demos/zhCN/index.demo-entry.md
> docs(icon): update xicons domain

- src/data-table/demos/enUS/custom-filter-menu.demo.vue
- src/data-table/demos/zhCN/custom-filter-menu.demo.vue
> docs(data-table): add example to render expand icon

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/src/HeaderButton/ResizeButton.tsx
- src/data-table/src/TableParts/Header.tsx
- src/data-table/src/interface.ts
- src/data-table/src/use-table-data.ts
- src/data-table/src/utils.ts
> refactor(data-table): resize column

- src/select/tests/Select.spec.tsx
> fix(select): optimize select test

- demo/pages/docs/community/enUS/index.md
- demo/pages/docs/community/zhCN/index.md
1. 修改GoView指向地址，指向到 gitee 项目
2. 优化项目说明，语言更加简洁
3. 新增英文版本项目地址，指向 github 地址
> docs: 修改社区精选资源-GoView-相关内容

- README.md
- README.zh-CN.md
- demo/pages/docs/installation/enUS/index.md
- demo/pages/docs/installation/zhCN/index.md
- demo/pages/home/Footer.vue
> docs: update design resources link

- src/result/tests/Result.spec.ts
> fix(result): optimize result test

- src/alert/tests/Alert.spec.ts
> fix(alert): optimize test

- src/anchor/tests/Anchor.spec.ts
> test(anchor): optimize test

- src/avatar/tests/Avatar.spec.tsx
> test(avatar): optimize test

- src/avatar-group/tests/Avatar.spec.tsx
> test(avatar-group): optimize test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/transfer/demos/enUS/index.demo-entry.md
- src/transfer/demos/zhCN/index.demo-entry.md
- src/transfer/src/Transfer.tsx
- src/transfer/src/use-transfer-data.ts
> feat(transfer): add `show-selected` prop

- src/back-top/tests/BackTop.spec.ts
> test(back-top): optimize test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/src/DataTable.tsx
> feat(data-table): add `loading` slot

- src/badge/tests/Badge.spec.ts
> test(badge): optimize test

- demo/pages/docs/i18n/enUS/index.md
- demo/pages/docs/i18n/zhCN/index.md
- src/locales/__snapshots__/index.spec.tsx.snap
> feat: optimize the #3945 PR

- src/carousel/tests/Carousel.spec.tsx
> chore(CI): solve error

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/src/styles/index.cssr.ts
> fix(tree): white screen appears when drag the tree on Chrome Edge version 106

- src/breadcrumb/tests/Breadcrumb.spec.ts
> test(breadcrumb): optimize test

- src/calendar/tests/Calendar.spec.tsx
> test(calendar): optimize test

- src/card/tests/Card.spec.ts
> test(card): optimize test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/demos/enUS/custom-thumb.demo.vue
> fix(slider_demo): change slot name to `#thumb` for custom thumb from `#header` (#3992)

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> docs(readme): fix readme

- src/cascader/tests/Cascader.spec.ts
> test(cascader): optimize test

- src/timeline/src/styles/index.cssr.ts
> feat(timeline): horizontal dash timeline

- src/color-picker/demos/enUS/actions.demo.vue
- src/color-picker/demos/enUS/index.demo-entry.md
- src/color-picker/demos/zhCN/actions.demo.vue
- src/color-picker/demos/zhCN/index.demo-entry.md
- src/color-picker/src/ColorPicker.tsx
- src/locales/common/arDZ.ts
- src/locales/common/deDE.ts
- src/locales/common/enGB.ts
- src/locales/common/enUS.ts
- src/locales/common/eo.ts
- src/locales/common/esAR.ts
- src/locales/common/frFR.ts
- src/locales/common/idID.ts
- src/locales/common/itIT.ts
- src/locales/common/jaJP.ts
- src/locales/common/koKR.ts
- src/locales/common/nbNO.ts
- src/locales/common/nlNL.ts
- src/locales/common/plPL.ts
- src/locales/common/ptBR.ts
- src/locales/common/ruRU.ts
- src/locales/common/skSK.ts
- src/locales/common/thTH.ts
- src/locales/common/ukUA.ts
- src/locales/common/viVN.ts
- src/locales/common/zhCN.ts
- src/locales/common/zhTW.ts
feat(color-picker): add clear action
> feat(color-picker): add clear action

- src/data-table/src/styles/index.cssr.ts
> fix(data-table): nested data-table hover style

- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
> feat(tree): optimize PR

- src/checkbox/tests/Checkbox.spec.tsx
> feat(checkbox): optimize test

- src/code/tests/Code.spec.ts
> test(code): optimize test

- src/collapse/tests/Collapse.spec.tsx
> test(collapse): optimize test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/pagination/src/Pagination.tsx
- src/pagination/tests/Pagination.spec.tsx
close [#4057](https://github.com/tusen-ai/naive-ui/issues/4057)
> fix(pagination): `endIndex` calc incorrect

- src/color-picker/tests/ColorPicker.spec.tsx
> test(color-picker): optimize test

- src/countdown/tests/Countdown.spec.ts
> test(countdown): optimize test

- src/data-table/tests/DataTable.spec.tsx
> test(data-table): optimize test

- src/anchor/demos/enUS/affix.demo.vue
- src/anchor/demos/enUS/basic.demo.vue
- src/anchor/demos/enUS/ignore-gap.demo.vue
- src/anchor/demos/enUS/scrollto.demo.vue
- src/anchor/demos/zhCN/affix.demo.vue
- src/anchor/demos/zhCN/basic.demo.vue
- src/anchor/demos/zhCN/ignore-gap.demo.vue
- src/anchor/demos/zhCN/scrollto.demo.vue
> docs(anchor): update demo

- src/date-picker/tests/DatePicker.spec.tsx
> test(date-picker): optimize test

- src/data-table/demos/zhCN/switchable-editable.demo.md
> docs(data-table): fix switchable editable demo

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/image/src/ImagePreview.tsx
> fix(image): preview toolbar error

- CHANGELOG.en-US.md
- src/card/demos/enUS/index.demo-entry.md
- src/card/src/Card.tsx
> feat: add tag property to Card

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/src/Tree.tsx
Fixes [#4134](https://github.com/tusen-ai/naive-ui/issues/4134).
> fix(nTree):  cannot access mergedFilterRef before initialization error

- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
> docs(tree): fix prop `checkable` desc

- src/input-number/demos/enUS/parse.demo.vue
- src/input-number/demos/zhCN/parse.demo.vue
I'm open to where this reminder should be placed.
close #4153
> docs(input-number): emphasize that the `parse` & `format` should both occur

- src/descriptions/tests/Descriptions.spec.ts
> test(descriptions): optimize test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/pagination/demos/enUS/index.demo-entry.md
- src/pagination/demos/zhCN/index.demo-entry.md
- src/pagination/src/Pagination.tsx
> feat(Pagination): add consistent-menu-width prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/ellipsis/src/Ellipsis.tsx
> fix(ellipsis): fix cannot be closed when using keep-alive

- src/tree-select/src/TreeSelect.tsx
> chore: fix lint error

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/locales/common/koKR.ts
i translated some words into korean
> feat(i18n): update korean translation

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/src/styles/input.cssr.ts
> fix(input): style bug of tiny size with autosize prop

- src/dialog/tests/Dialog.spec.tsx
> test(dialog): optimize test

- src/divider/tests/Divider.spec.ts
> test(divider): optimize test

- src/dynamic-tags/tests/DynamicTags.spec.ts
> test(dynamic-tags): optimize test

- src/element/tests/Element.spec.ts
> test(element): optimize test

- src/ellipsis/tests/Ellipsis.spec.tsx
> test(ellipsis): optimize test

- src/data-table/demos/enUS/switchable-editable.demo.md
- src/data-table/demos/zhCN/switchable-editable.demo.md
完善了可编辑的 n-data-table 的 demo
相关 [#4118](https://github.com/tusen-ai/naive-ui/issues/4118)
> docs(data-table): optimize docs

- CHANGELOG.en-US.md
> docs: optimize readme

- src/form/tests/Form.spec.tsx
> test(form): optimize test

- src/gradient-text/tests/GradientText.spec.ts
> test(gradient-text): optimize test

- src/grid/tests/Grid.spec.tsx
> test(grid): optimize test

- src/icon/tests/Icon.spec.ts
> test(icon): optimize test

- src/image/tests/Image.spec.tsx
> test(image): optimize test

- src/input-number/tests/InputNumber.spec.tsx
> test(input-number): optimize test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/scrollbar/demos/enUS/index.demo-entry.md
- src/scrollbar/demos/zhCN/index.demo-entry.md
- src/scrollbar/src/Scrollbar.tsx
> feat: scrollbar add size prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/index.demo-entry.md
- src/select/src/Select.tsx
> feat: select add keyboard prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/src/TableParts/ExpandTrigger.tsx
- src/data-table/src/interface.ts
> feat(data-table): `render-expand-icon` add `expanded` param

- src/legacy-transfer/tests/Transfer.spec.ts
> test(transfer): optimize test

- src/tree/demos/enUS/file-tree.demo.vue
- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/file-tree.demo.vue
- src/tree/demos/zhCN/index.demo-entry.md
> docs: add demo for file tree

- src/tree/demos/enUS/file-tree.demo.vue
- src/tree/demos/zhCN/file-tree.demo.vue
> docs(tree): fix file-tree error

- src/tree/demos/enUS/file-tree.demo.vue
- src/tree/demos/zhCN/file-tree.demo.vue
> docs(tree): optimize file-tree

- src/list/tests/List.spec.ts
> feat(list): optimize test

- src/log/tests/Log.spec.tsx
> test(log): optimize test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/locales/common/zhTW.ts
> feat: translate zhTw locales

- src/mention/tests/Mention.spec.ts
> test(mention): optimize test

- src/menu/tests/Menu.spec.tsx
> test(menu): optimize test

- src/notification/tests/Notification.spec.tsx
> test(notification): optimize test

- src/page-header/tests/PageHeader.spec.tsx
> test(page-header): optimize test

- src/pagination/tests/Pagination.spec.tsx
> test(pagination): optimize test

- src/popconfirm/tests/Popconfirm.spec.ts
> test(popconfirm): optimize test

- src/progress/tests/Progress.spec.ts
> test(progress): optimize test

- src/radio/tests/Radio.spec.ts
> test(radio): optimize test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/notification/src/styles/index.cssr.ts
> fix(notification): `description` does not wrap when there is English

- src/skeleton/tests/Skeleton.spec.tsx
> test(skeleton): optimize test

- src/tabs/tests/Tabs.spec.tsx
> chore(lint): fixed error

- src/slider/tests/Slider.spec.ts
> test(slider): optimize test

- .github/workflows/node.js.yml
> chore(action): cancel verification of node 14.X, add verification of node 18.x

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- demo/pages/docs/i18n/enUS/index.md
- demo/pages/docs/i18n/zhCN/index.md
- src/locales/__snapshots__/index.spec.tsx.snap
- src/locales/common/faIR.ts
- src/locales/index.spec.tsx
> feat(locales): optimize faIR locale

- src/space/tests/Space.spec.tsx
> test(space): optimize test

- .github/workflows/node.js.yml
> ci: bump up actions

- src/scrollbar/demos/enUS/index.demo-entry.md
- src/scrollbar/demos/zhCN/index.demo-entry.md
docs(n-scrollbar): add `size` prop.
> docs(n-scrollbar): add size prop.

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/collapse/src/Collapse.tsx
- src/collapse/src/styles/index.cssr.ts
- src/collapse/styles/light.ts
> feat(collapse): add `titlePadding` theme variable

- src/breadcrumb/src/BreadcrumbItem.tsx
> chore: remove console

- src/popover/src/Popover.tsx
> feat(popover): replace `createTextVNode` width `Text`

- src/spin/tests/Spin.spec.ts
> test(spin): optimize

- src/statistic/tests/Statistic.spec.ts
> test(statistic): optimize test

- demo/pages/docs/common-issues/enUS/index.md
- demo/pages/docs/common-issues/zhCN/index.md
- demo/pages/docs/usage-sfc/enUS/index.md
- demo/pages/docs/usage-sfc/zhCN/index.md
> docs: optimize docs about SFC

- src/drawer/src/Drawer.tsx
- src/drawer/src/DrawerBodyWrapper.tsx
when resizable is enabled you can set max or min size for drag
> feat(drawer): resizable support max and min size

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
ref https://github.com/tusen-ai/naive-ui/discussions/4890
> docs(n-data-table):  add on-scroll docs

- src/_utils/vue/call.ts
> style: change AnyFuction to AnyFunction

- demo/pages/docs/umd/enUS/index.md
- demo/pages/docs/umd/zhCN/index.md
> docs(UMD): Add an alert for tag-closing bug

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popconfirm/src/Popconfirm.ts
- src/popover/src/interface.ts
> fix(popconfirm): action button can be triggered multiple times

- src/data-table/index.ts
> feat(data-table): export TableColumnGroup

- src/upload/src/Upload.tsx
the `RenderIcon` is a function but set the `Object` constructor.
> fix: upload component types

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
> Update doc DataTableColumn titleAlign version

- src/timeline/demos/enUS/index.demo-entry.md
See typo here: [https://www.naiveui.com/en-US/light/components/timeline#:~:text=world%20is%202-,demensioned,-.%20One%20of%20them](https://www.naiveui.com/en-US/light/components/timeline#:~:text=world%20is%202-,demensioned,-.%20One%20of%20them)
Accidentally forked the wrong branch in the other pull request, this one's the good one.
> docs: fixed typo "demensioned" in Timeline component

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tabs/src/Tabs.tsx
复现代码：<https://codesandbox.io/s/dazzling-moore-t565nh?file=/src/Demo.vue>
> Fix n-tabs paneWrapperStyle prop missing height after animation

- src/checkbox/tests/Checkbox.spec.tsx
- src/spin/tests/Spin.spec.ts
- volar.d.ts
> test(checkbox): checkbox may not have label this test is no need

- themes/tusimple/src/TsConfigProvider.tsx
- themes/tusimple/src/icons.tsx
- themes/tusimple/src/use-ts-dialog.ts
- themes/tusimple/src/use-ts-message.ts
> fix: consistent-type-imports

- demo/pages/docs/community/enUS/index.md
- demo/pages/docs/community/zhCN/index.md
* docs(select): Description error for 'show-checkmark'
* docs(select): Description error for 'show-checkmark'
> docs: add community resources

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/locales/common/zhTW.ts
Improve zhTW Traditional Chinese locale 🎉
> Update zhTW.ts, improve some translation

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/HeaderButton/ResizeButton.tsx
> fix(data-table): drag column causing text selection in Safari

- src/auto-complete/src/AutoComplete.tsx
- src/auto-complete/src/interface.ts
- src/data-table/src/TableParts/Header.tsx
- src/locales/__snapshots__/index.spec.tsx.snap
- fix auto-complete type define
- update snapshot
> fix(auto-complete): enhance type

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/loading-bar/demos/zhCN/container.demo.vue
- src/loading-bar/src/LoadingBar.tsx
> fix(loading-bar): `useLoadingBar` can't finish loading when called `finish` method

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> docs(changelog): optimize formatting and translation

- src/time-picker/demos/zhCN/index.demo-entry.md
- src/time/demos/zhCN/index.demo-entry.md
> docs: fix word error in Chinese docs 

- demo/pages/docs/community/enUS/index.md
- demo/pages/docs/community/zhCN/index.md
> docs: add community resource

- src/dialog/demos/zhCN/index.demo-entry.md
> docs(dialog): Attribute Description Supplement

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/clear/src/Clear.tsx
- src/auto-complete/demos/enUS/basic.demo.vue
- src/auto-complete/demos/zhCN/basic.demo.vue
> fix(clear): invoke clear on mousedown

- src/input/src/Input.tsx
> feat(input): optimize `on-keyup`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_utils/vue/flatten.ts
- src/space/src/Space.tsx
reverts tusen-ai/naive-ui#5150, cc https://github.com/tusen-ai/naive-ui/issues/824
> revert(space): omitting comment VNode in space

- .github/workflows/node.js.yml
> chore(ci): parallel

- .github/workflows/node.js.yml
> chore(ci): node 16 EFO drop it

- src/statistic/demos/enUS/index.demo-entry.md
- src/statistic/demos/zhCN/index.demo-entry.md
> docs(statistic): update props value

- src/cascader/demos/enUS/single-lazy.demo.vue
Update single-lazy cascader placeholder in enUS to English.
> fix: update single-lazy cascader placeholder to enUS

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/scrollbar/src/Scrollbar.tsx
> fix(input): textarea not display scrollbar when `inline-theme-disabled`

- src/tabs/src/styles/index.cssr.ts
> fix(tabs): vertical mode border height

- src/locales/common/frFR.ts
> fix fr-FR firstDayOfWeek

- src/data-table/src/DataTable.tsx
> refactor(type): remove @typescript-eslint/type-assertions

- src/_mixins/use-form-item.ts
- src/tree-select/src/TreeSelect.tsx
- src/tree-select/src/utils.ts
- src/tree/src/utils.ts
> refactor(type): remove useless any

- src/checkbox/demos/enUS/event.demo.vue
this is similar to this PR https://github.com/tusen-ai/naive-ui/pull/5178 but in a different component
> Fixed checkbox value and label attributes mismatching in event.demo.vue

- src/checkbox/demos/enUS/group.demo.vue
Small mismatch of between value and label
> Fixed checkbox value and label attributes mismatching in group.demo.vue

- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
> docs(tree): 补充 tree 组件的 slot 文档

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/src/styles/index.cssr.ts
> fix(tree): leaf node line color

- demo/pages/docs/controlled-uncontrolled/zhCN/index.md
> <fix> 修改语义问题.

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/src/Tree.tsx
close [#5217 ](https://github.com/tusen-ai/naive-ui/issues/5217)
> fix(n-tree): 解决issue #5217中所提的-Tree组件数据渲染错误问题 (#5217)

- src/split/src/Split.tsx
- src/split/styles/light.ts
> fix: Use the split component alone. There is no default color.

- demo/pages/docs/import-on-demand/enUS/index.md
- demo/pages/docs/ssr/enUS/index.md
- demo/pages/docs/ssr/zhCN/index.md
- Added instructions about using auto import in Nuxt.
- Fixed a typo.
- Updated the link for docs about configuring Nuxt.
- 添加了在 Nuxt 中使用自动引入的说明。
- 修正了一个拼写错误。
- 更新了关于配置 Nuxt 的文档链接。
> docs(ssr): Adding instructions about using auto import in Nuxt and some fixes

- src/drawer/demos/enUS/index.demo-entry.md
> docs(drawer): translate scrollbar props description

- demo/pages/docs/controlled-uncontrolled/zhCN/index.md
修改【controlled-uncontrolled】文档语义问题.
> docs：【controlled-uncontrolled】语义问题修改

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/bug_report.zh-CN.yml
> chore: fix typo with envinfo

- src/split/demos/enUS/event.demo.vue
- src/split/demos/zhCN/event.demo.vue
> docs(split): update event demo

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/auto-complete/demos/enUS/append.demo.vue
- src/auto-complete/demos/enUS/index.demo-entry.md
- src/auto-complete/demos/zhCN/append.demo.vue
- src/auto-complete/demos/zhCN/index.demo-entry.md
- src/auto-complete/src/AutoComplete.tsx
- src/auto-complete/tests/AutoComplete.spec.ts
[adds append prop for auto-complete](https://github.com/tusen-ai/naive-ui/issues/5591)
> feat(auto-complete): adds append prop

- src/locales/__snapshots__/index.spec.tsx.snap
> test: snapshot

- .github/workflows/node.js.yml
> chore(ci): add lts node 20

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/qr-code/demos/enUS/color.demo.vue
- src/qr-code/demos/zhCN/color.demo.vue
- src/qr-code/src/QrCode.tsx
> fix(qr-code): style of size

- package.json
- src/checkbox/tests/Checkbox.spec.tsx
- src/dropdown/src/Dropdown.tsx
- src/dropdown/tests/Dropdown.spec.tsx
- src/dynamic-input/demos/enUS/form.demo.vue
- src/dynamic-input/demos/zhCN/form.demo.vue
- src/layout/src/LayoutFooter.tsx
- src/layout/src/LayoutHeader.tsx
- src/menu/src/Menu.tsx
- src/menu/tests/Menu.spec.tsx
- src/switch/tests/Switch.spec.tsx
- src/upload/src/Upload.tsx
- src/upload/tests/Upload.spec.tsx
- themes/tusimple/src/icons.tsx
- tsconfig.json
> chore(deps): bump to vue3.4

- README.zh-CN.md
- demo/pages/home/Footer.vue
> chore: delete invalid links

- .github/ISSUE_TEMPLATE/bug_report.zh-CN.yml
- .github/ISSUE_TEMPLATE/feature_request.zh-CN.yml
> chore: fix cn issue templates

- .github/workflows/node.js.yml
Using new M1 macOS runner to make CI faster.
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> using new M1 macOS runner

- src/discrete/src/discreteApp.ts
- src/discrete/src/interface.ts
> fix(modal): Add modal functionality to DiscreteApp

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
add the update time 
based on `https://github.com/tusen-ai/naive-ui/tags`
添加naive-ui 版本更新时间
基于tags `https://github.com/tusen-ai/naive-ui/tags`
> docs(CHANGELOG)：add the update time

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/card/demos/enUS/index.demo-entry.md
- src/card/demos/zhCN/index.demo-entry.md
- src/card/src/Card.tsx
- src/modal/demos/enUS/reactive.demo.vue
- src/modal/demos/zhCN/reactive.demo.vue
- src/modal/src/ModalProvider.ts
> fix(useModal): `card` preset without corresponding props in `n-card` slots

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dialog/src/DialogProvider.ts
- src/modal/src/ModalProvider.ts
> fix(dialog,modal): call `destroy` method may throw error

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tabs/src/styles/index.cssr.ts
> fix(tabs): style bug with type is `segment`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/watermark/src/Watermark.tsx
> feat(watermark): support multi lines in content

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_mixins/use-theme.ts
https://github.com/tusen-ai/naive-ui/issues/5719#issuecomment-1963972917
> fix: `common` type error in `theme-overrodes` prop

- CHANGELOG.en-US.md
- src/slider/src/Slider.tsx
- src/slider/tests/Slider.spec.ts
Slider support aria. Link #41.
References:
1. https://www.w3.org/WAI/ARIA/apg/patterns/slider/
2. https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/
3. https://w3c.github.io/aria/#slider
> feat(slider): aria support

- src/split/src/Split.tsx
> fix(split): fix themeClassHandle name

- src/_internal/scrollbar/src/styles/index.cssr.ts
> fix(scrollbar): parent element collapses in height (#4497)

- package.json
- src/form/src/FormItem.tsx
- src/infinite-scroll/src/InfiniteScroll.tsx
- src/locales/__snapshots__/index.spec.tsx.snap
- fix type define error in https://github.com/tusen-ai/naive-ui/pull/5669
- handle null in https://github.com/tusen-ai/naive-ui/pull/5546
- downgrade eslint-markdown it https://github.com/tusen-ai/naive-ui/pull/5765,it cause https://github.com/tusen-ai/naive-ui/issues/5815
> fix: FormItem props type define,InfiniteScroll null safe

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
> fix: Fix bugs in `DataTable` documentation

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/demos/enUS/index.demo-entry.md
- src/input-number/demos/zhCN/index.demo-entry.md
- src/input-number/src/InputNumber.tsx
close https://github.com/tusen-ai/naive-ui/issues/6097
> feat(n-input-number): add `round` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/color-picker/demos/enUS/index.demo-entry.md
- src/color-picker/demos/zhCN/index.demo-entry.md
- src/color-picker/src/ColorPicker.tsx
- src/color-picker/src/interface.ts
> feat(Color Picker): add on-clear props

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/FormItem.tsx
- src/form/tests/Form.spec.tsx
fix #6068 
- removes unnecessary checks
- set the verification status correctly
> fix(form): ensure validation state is correctly updated(#6068)

- src/form/demos/enUS/index.demo-entry.md
- src/form/demos/zhCN/index.demo-entry.md
There should be a string, not a typo ( number --> Number, which I thouglt firstly..)
> chore: reduce confusion

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/select/src/Select.tsx
> fix(select): select组件的 header 插槽里 input 无法输入，关闭 #6030

- src/upload/src/UploadFile.tsx
fix: https://github.com/tusen-ai/naive-ui/issues/6036
> fix: upload on preview prevent default

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/src/Tree.tsx
> fix(tree): Fix filtering and checking exceptions in `Tree` when `show-irrelevant-nodes` is `false`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/scrollbar/src/Scrollbar.tsx
- src/_internal/scrollbar/src/styles/index.cssr.ts
- src/_internal/scrollbar/styles/common.ts
- src/scrollbar/demos/enUS/index.demo-entry.md
- src/scrollbar/demos/enUS/placement.demo.vue
- src/scrollbar/demos/zhCN/index.demo-entry.md
- src/scrollbar/demos/zhCN/placement.demo.vue
- src/scrollbar/src/Scrollbar.tsx
> feat(scrollbar): add `x-placement` and `y-placement` props.

- src/data-table/demos/zhCN/fixed-column-debug.demo.md
> fix(data-table): createData function

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/cascader/src/CascaderSelectMenu.tsx
> feat(cascader): filter ignore case sensitive

- src/transfer/src/Transfer.tsx
> fix(lint): space

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/icon/src/Icon.ts
> fix(icon): `component` prop not accepting FunctionalComponent

- src/mention/src/Mention.tsx
fixed: https://github.com/tusen-ai/naive-ui/issues/6241
> fix: mention panel position error

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/image/demos/enUS/custom-error.demo.vue
- src/image/demos/enUS/index.demo-entry.md
- src/image/demos/zhCN/custom-error.demo.vue
- src/image/demos/zhCN/index.demo-entry.md
- src/image/src/Image.tsx
close [#5649](https://github.com/tusen-ai/naive-ui/issues/5649)
> feat(n-image): add `error` slot

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/time-picker/src/PanelCol.tsx
close [#4308](https://github.com/tusen-ai/naive-ui/issues/4308)
> fix(n-time-picker):`use-12-hours` type error warning

- src/carousel/src/Carousel.tsx
close https://github.com/tusen-ai/naive-ui/issues/6407
close https://github.com/tusen-ai/naive-ui/issues/6500
> chore(carousel): api usage updated to be compatible with Vue3.5.0

- CHANGELOG.zh-CN.md
- src/_internal/scrollbar/src/Scrollbar.tsx
- src/_internal/scrollbar/src/styles/index.cssr.ts
- src/_utils/css/rtl-inset.ts
- src/float-button-group/src/styles/index.cssr.ts
- src/float-button/src/styles/index.cssr.ts
- src/loading-bar/demos/enUS/container.demo.vue
- src/loading-bar/demos/zhCN/container.demo.vue
- src/popover/src/Popover.tsx
close [#6604](https://github.com/tusen-ai/naive-ui/issues/6604)，close [#6602](https://github.com/tusen-ai/naive-ui/issues/6602)
> fix: 修改 inset 属性，因为在部分浏览器中有兼容性问题

- src/data-table/demos/enUS/controlled-sorter.demo.vue
- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/controlled-sorter.demo.vue
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/index.ts
- controlled-sorter ts demo
- export type `DataTableSortOrder`
- fix wrong prop `defaultFilter` to `defaultFilterOptionValues`
> docs(data-table): ts demo

- src/locales/__snapshots__/index.spec.tsx.snap
> test(locales): update snapshots

- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
> docs(tree): add  indent props

- src/_internal/icon/src/styles/index.cssr.ts
- src/icon/src/styles/index.cssr.ts
- src/tree/src/styles/index.cssr.ts
> fix: remove unnecessary transforms to reduce layer count and improve scrolling performance

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popover/src/PopoverBody.tsx
- src/popover/styles/dark.ts
- src/popover/styles/light.ts
> fix(popover): scrollbar's themeOverrides configuration is not injected into the popover

- .github/ISSUE_TEMPLATE/bug_report.yml
- demo/pages/docs/community/enUS/index.md
- demo/pages/docs/community/zhCN/index.md
- demo/utils/ComponentDemo.vue
- demo/utils/EditInPlaygroundButton.vue
- demo/utils/playground.js
- package.json
- src/dynamic-tags/demos/enUS/slot.demo.vue
- src/dynamic-tags/demos/zhCN/slot.demo.vue
- src/select/demos/enUS/custom-suffix.demo.vue
- src/select/demos/zhCN/custom-suffix.demo.vue
- src/slider/demos/enUS/custom-marks.demo.vue
- src/slider/demos/zhCN/custom-marks.demo.vue
> feat: edit in playground for demo

- src/_utils/naive/prop.ts
> refactor(prop): simplify size mapping functions

- src/anchor/src/BaseAnchor.tsx
- src/image/src/Image.tsx
- src/image/src/ImageGroup.tsx
- src/locales/common/daDK.ts
- add missing `Heatmap` to `daDK`
- fix `Image` `ImageGroup` `Anchor` type define issue
> fix: locales & type

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-otp/demos/enUS/index.demo-entry.md
- src/input-otp/demos/zhCN/index.demo-entry.md
- src/input-otp/src/InputOtp.tsx
- src/input-otp/src/public-types.ts
close https://github.com/tusen-ai/naive-ui/issues/7073
提供focusOnChar方法
> feat: `n-input-otp` adds `focusOnChar` util method

- demo/pages/docs/community/enUS/index.md
- demo/pages/docs/community/zhCN/index.md
> 📃 docs: 社区精选资源新增rengar admin
