tusen-ai/naive-ui

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/src/Input.tsx
In the document, the "input" component supports the "password" type, but it is not declared in the code.
在文档里，"input"组件支持"password"类型，但代码里面未声明
> fix(input): add 'password' declaration for 'input'

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/button/src/styles/button.cssr.ts
- Naive UI version: (eg. 2.11.0)
- Browser Info: ( Chome 91)
- System Info: (Windows 10 21H1)
- Create a static html site
- Build a naive app with a nbutton
- Include app js to head of html file
- App crash, nothing show
- because app js was included to head, so `document.body` is null. Use `document.createElement('div')` instead.
> Fix crash when load app in head tag

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/src/Slider.tsx
Hello ^-^. Right now the Slider component doesn't work well on mobile devices, because it doesn't react to touchstart/touchmove and touchend events. This pr will fix it.
> fix: add touch events support for slider

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/color-picker/demos/enUS/index.demo-entry.md
- src/color-picker/demos/enUS/modes.demo.md
- src/color-picker/demos/zhCN/index.demo-entry.md
- src/color-picker/demos/zhCN/modes.demo.md
- src/color-picker/src/ColorInput.tsx
- src/color-picker/src/ColorPicker.tsx
- src/color-picker/src/styles/index.cssr.ts
- src/color-picker/tests/ColorPicker.spec.tsx
> fix(color-picker): change modes not working

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/styles/form-item.cssr.ts
> fix: n-form-item's grid-template-columns

- src/button/demos/zhCN/rtl-debug.demo.md
the origin example seem to be unresponsive，so add icons to make `RTL` more obvious
> docs(button): optimizate button rtl demo

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/cascader/src/styles/index.cssr.ts
Remove the overflow property of the 'n-cascader-submenu' class
> fix(cascader): Fix `n-cascader` text blur in win10 Chrome.

- src/form/src/utils.ts
- src/transfer/demos/enUS/index.demo-entry.md
修复 FormItem 覆盖自定义宽度，以及 rem 无效的 bug
> fix: form-item custom width override

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/carousel/src/Carousel.tsx
> feat(carousel): touch operation

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- package.json
- src/_internal/select-menu/src/SelectMenu.tsx
- src/select/demos/zhCN/menu-debug.demo.md
> fix(select): doesn't scroll to selected item when menu is opened

- src/menu/demos/enUS/select.demo.md
Added the missing "s" in word "firt".
为单词 “firt” 添加缺失的字母 “s”。
> Fix a typo in select.demo.md

- src/input/src/Input.tsx
input输入框在设置clearable后，会有设置readonly属性，清除按钮依然显示的问题。这样设置了readonly属性，依然可以通过清除按钮清空input输入框内容，不符合一般逻辑。这次PR让showClearButton多判断了是否设置readonly属性
> fix(input)：修改input输入框设置只读后，清除按钮依然显示的问题

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/styles/index.cssr.ts
Fix: #663 
https://codesandbox.io/s/floral-mountain-pxlen?file=/src/Demo.vue
> fix(data-table): spin style penetration

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/demos/enUS/icon.demo.md
- src/input-number/demos/enUS/index.demo-entry.md
- src/input-number/demos/zhCN/icon.demo.md
- src/input-number/demos/zhCN/index.demo-entry.md
- src/input-number/src/InputNumber.tsx
- src/input-number/src/styles/input-number.cssr.ts
- src/input-number/tests/InputNumber.spec.tsx
- src/input/src/styles/input.cssr.ts
> feat(inputNumber): add NInputNumber slots

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_styles/common/dark.ts
- src/_styles/common/light.ts
- src/scrollbar/src/ScrollBar.tsx
- src/scrollbar/src/styles/index.cssr.ts
> feat(scrollbar): add some variables

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/src/Slider.tsx
fix floating point decimal precision
修复 `n-slider` 的浮点数小数精度丢失
issue
close #751
> fix(slider): fix floating point decimal precision

- src/anchor/demos/enUS/basic.demo.md
The `:show-rail` and `:show-background` attributes were used for the
basic demo for zhCN, but not for enUS. This adds those attributes to be
used in the basic demo for enUS, too.
> docs(anchor): Add `show-rail` & `show-background`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/message/demos/enUS/index.demo-entry.md
- src/message/demos/zhCN/index.demo-entry.md
- src/message/src/MessageProvider.tsx
> feat(message): messageProvider add closable prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/avatar/demos/enUS/index.demo-entry.md
- src/avatar/demos/zhCN/index.demo-entry.md
- src/avatar/demos/zhCN/v-show-debug.demo.md
- src/avatar/src/Avatar.tsx
这一次精简了代码，也更安全了，希望能够采纳
fix #779
> fix(avatar): scale value is incorrect

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/use-check.ts
fix [#778](https://github.com/TuSimple/naive-ui/issues/778).
> fix(data-table): When selectAll is selected, the state display of selectAll should not contain disabled rows

- src/menu/demos/enUS/render-label.demo.md
- src/menu/demos/zhCN/render-label.demo.md
- src/menu/tests/Menu.spec.ts
ref: https://github.com/TuSimple/naive-ui/commit/7cb72375aa1ca5ba68a33140a6f68d9139328a3f
```javascript
function renderMenuIcon (option: any): any {
// return comment vnode, render placeholder for indent
if (option.key === 'mojito') return h(() => null)
// return falsy, don't render icon placeholder
if (option.key === 'initialj') return null
// otherwise, render returns vnode
return h(NIcon, null, { default: () => h(HappyOutline) })
}
```
> test(NMenu): fix menu render-icon test cases

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/message/src/MessageProvider.tsx
- src/message/tests/Message.spec.tsx
The title says it all.
Inspired by `<n-layout>`'s prop `content-style`, this allows the user to add arbitrary styles to the `<div class="n-message-container">`, allowing the user to change the position and the flex options of the container, to have fine grained control of how messages are shown.
> feat(message): Add `container-style` prop to `n-message-provider`

- src/carousel/demos/enUS/dot-placement.demo.md
- src/carousel/demos/enUS/hover.demo.md
- src/carousel/demos/enUS/index.demo-entry.md
- src/carousel/demos/zhCN/dot-placement.demo.md
- src/carousel/demos/zhCN/hover.demo.md
I found the autoplaying confusing as to what was different between these.
I think the autoplay should be left for only the autoplay example so you can explore the specific differences of the other examples.
> Docs(NCarousel) Remove autoplay from non-autoplay examples

- src/transfer/tests/Transfer.spec.ts
> test(transfer): add test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/timeline/demos/enUS/horizontal.demo.md
- src/timeline/demos/enUS/index.demo-entry.md
- src/timeline/demos/zhCN/horizontal.demo.md
- src/timeline/demos/zhCN/index.demo-entry.md
- src/timeline/src/Timeline.tsx
- src/timeline/src/styles/index.cssr.ts
- src/timeline/tests/Timeline.spec.ts
close https://github.com/TuSimple/naive-ui/issues/887
> feat(timeline): add `horizontal` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/src/InputNumber.tsx
- src/input-number/tests/InputNumber.spec.tsx
> fix: input-number add error

- src/select/src/Select.tsx
Fix the type mismatch problem when using null as a zero value
> type(Select): update value type

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/descriptions/src/Descriptions.tsx
close https://github.com/TuSimple/naive-ui/issues/1083
> feat(description):Remove warnings caused by 'v-if' that should not appear

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
data-table文档缺失default-expanded-row-keys #1068
> docs(data-table):add default-expanded-row-keys prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/demos/enUS/index.demo-entry.md
- src/form/demos/zhCN/index.demo-entry.md
- src/form/src/Form.tsx
- src/form/src/FormItem.tsx
- src/form/src/utils.ts
- src/form/tests/Form.spec.tsx
NOTE: BREAKING CHANGE
close #1055.
> feat(form): split require-mark-placement and show-require-mark

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/FormItemGridItem.ts
- src/grid/src/GridItem.tsx
> Fix(form): Collpsed in FormItemGi does not work

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/badge/src/styles/index.cssr.ts
> fix(badge): fix `n-button` border on hover conflicts with `n-badge`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/upload/src/Upload.tsx
- src/upload/src/UploadFile.tsx
- src/upload/src/interface.ts
> fix(upload): fix `show-preview-button` not working

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/layout/src/LayoutSider.tsx
- src/layout/src/styles/layout-sider.cssr.ts
- src/layout/styles/dark.ts
- src/layout/styles/light.ts
不知这么处理是否合适，还请多多指教。
问题：layoutSider 在 inverted 模式下，siderToggleButton的字体颜色会变成白色，跟背景融合在一起。可查看文档中的反转案例。[文档地址](https://www.naiveui.com/zh-CN/os-theme/components/layout)
解决方式：添加了siderToggleButtonTextColor，默认为textColor2。使其颜色与layout的textColor解耦，同时跟siderToggleBar一样可单独设置样式。
Question: Under the inverted mode of layoutSider, the font color of siderToggleButton would turn white and merge with its backgroundColor.    
Solution: Add siderToggleButtonTextColor, textColor2 on by default.  Decouple the color inherited from the Layout's textColor, and we can set its style separately, same with siderToggleBar.
> feat(layoutSider): add ToggleButtonTextColor

- .github/workflows/node.js.yml
1. node 16 has become the LTS version 
https://nodejs.org/en/about/releases/
2. action `codecov/codecov-action` has new version @v2.1.0 
https://github.com/codecov/codecov-action/releases
> ci:add node 16 to matrix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/demos/enUS/index.demo-entry.md
- src/input/demos/enUS/input-props.demo.md
- src/input/demos/zhCN/index.demo-entry.md
- src/input/demos/zhCN/input-props.demo.md
- src/input/src/Input.tsx
fix `input-props` does not override properly
add some doc about `input-pops`
add warning in API table
close #1553
> fix(input):input-props override the props

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_styles/global/index.cssr.ts
- src/_styles/transitions/icon-switch.cssr.ts
Hi,
There is a bug on Vitejs when using a javascript object in string interpolation.
Therefore when building Nuxt app with Vitejs, we got an undefined commonVariables.
This PR solves this problem and should solve #636 
In defineNuxtConfig function we don't need to add vite: false anymore.
> Update styles to bypass Vitejs bug on string interpolation

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/auto-complete/demos/enUS/index.demo-entry.md
- src/auto-complete/demos/zhCN/index.demo-entry.md
- src/auto-complete/src/AutoComplete.tsx
- src/auto-complete/tests/AutoComplete.spec.ts
> feat(autoComplete): add inputProps prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dropdown/src/DropdownOption.tsx
- src/dropdown/src/utils.ts
> Fix(dropdown) transition shifts in cascade dropdown with anchor option

- src/modal/demos/enUS/index.demo-entry.md
- src/modal/demos/zhCN/index.demo-entry.md
> docs: Add missing types to 'preset' of Modal props

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/badge/src/Badge.tsx
- src/badge/src/styles/index.cssr.ts
- src/badge/tests/Badge.spec.ts
> feat(badge): badge uses n as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/back-top/src/BackTop.tsx
- src/back-top/src/styles/index.cssr.ts
> feat(back-top): use `n` as CSS vars prefix

- .github/workflows/issue-open-check.yml
use `check-issue-ref` to get the issue ref
enable issue opened by tacking issue convert to issue
> ci: use check-issue-ref enable tacking issue

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/FormItemCol.ts
- src/form/src/FormItemGridItem.ts
- src/form/src/FormItemRow.ts
> fix: FormItemGi does not work

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/progress/src/Progress.tsx
- src/progress/src/styles/index.cssr.ts
> feat(progress): progress uses n as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/collapse-transition/src/CollapseTransition.tsx
> feat(collapse-transition): uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/clear/src/styles/index.cssr.ts
> feat(internal):`base-clear` uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/close/src/styles/index.cssr.ts
> feat(internal):`base-close` uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/demos/enUS/index.demo-entry.md
- src/input-number/demos/enUS/loading.demo.md
- src/input-number/demos/zhCN/debug.demo.md
- src/input-number/demos/zhCN/index.demo-entry.md
- src/input-number/demos/zhCN/loading.demo.md
- src/input-number/src/InputNumber.tsx
- src/input-number/tests/InputNumber.spec.tsx
- src/input/demos/enUS/index.demo-entry.md
- src/input/demos/enUS/loading.demo.md
- src/input/demos/zhCN/index.demo-entry.md
- src/input/demos/zhCN/loading.demo.md
add `loading` prop for `input-number`
close #1984
> feat(input-number): add loading prop

- demo/utils/EditInCodeSandboxButton.vue
- demo/utils/EditOnGithubButton.vue
- demo/utils/github-url.js
Refactor `<EditOnGithubButton>` and `<EditInCodeSandboxButton>` to use native `<a>` and `<form>` elements.
Native elements retain expected functionalities and accessibility. A good read about this: [Stop breaking links with JavaScript](https://blog.matsu.io/stop-breaking-links-with-javascript)
> docs: use native anchor and form elements

- src/modal/demos/zhCN/index.demo-entry.md
The current version of the document does not have these two attributes, but I feel that they are still quite commonly used so I added them
> docs(modal): add onClose and onMaskClick properties

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/back-top/src/BackTop.tsx
This is just about the type of the prop since it was not yet supported. Though, the code already handles it, e.g. https://github.com/TuSimple/naive-ui/blob/main/src/back-top/src/BackTop.tsx#L177
> fix: allow Document type for listenTo prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/code/demos/enUS/index.demo-entry.md
- src/code/demos/enUS/softwrap.demo.vue
- src/code/demos/zhCN/index.demo-entry.md
- src/code/demos/zhCN/softwrap.demo.vue
- src/code/src/Code.tsx
- src/code/src/styles/index.cssr.ts
- src/code/tests/Code.spec.ts
add `word-wrap` prop
close #2111
> feat(code): add `word-wrap` prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/FormItem.tsx
- src/form/tests/Form.spec.tsx
This PR adds a `for` prop to the `FormItem` component to specify which form element the label is bound to.
> feat: add `for` prop to FormItem

- src/color-picker/src/ColorPicker.tsx
- src/color-picker/tests/ColorPicker.spec.tsx
I noticed that the single mode (other than RGB) of the `ColorPicker` does not work as soon as you use an empty string and instead the default RGB picker will be offered.
> fix: handle empty string and single mode other than RGB in `ColorPicker`

- package.json
After pnpm releases the version of `v6.26.0`, the warning can be ignored at the config, releases notes: https://github.com/pnpm/pnpm/releases/tag/v6.26.0
Before: 
After:
> fix: mute types of peer dependency warnings of pnpm

- src/composables/use-theme-vars.ts
- src/config-provider/src/interface.ts
It would be cool to make the theme type augmentable so we can use extend the theme with custom variables `useTheme`. An extension could look like this:
```typescript
import 'naive-ui';
declare module 'naive-ui' {
export interface ThemeCommonVarsExtension {
primaryColorActive: string
}
}
```
> feat: export ThemeCommonVars and make type augmentable

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/styles/form-item.cssr.ts
This PR will prevent the padding to be applied to the feedback container as long as there is no feedback to be displayed.
> fix: fix prevent feedback padding

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/use-table-data.ts
> fix(data-table): fix cannot click selection checkbox

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/locales/common/frFR.ts
Fix locale frFR missing translation for `Image`.
Also improved an existing translation on `ThemeEditor.title` (very minor change).
> fix(locale): locale frFR missing translation for Image

- src/data-table/demos/enUS/custom-style.demo.md
- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/custom-style.demo.md
- src/data-table/demos/zhCN/index.demo-entry.md
Prop `row-class-name` was typed by interface `CreateRowClassName` a year ago in commit [42be41d](https://github.com/TuSimple/naive-ui/commit/42be41dc4b1ddff31bd1b8d7f31196ebf401df5a)
Whose `ReturnType` has been narrowed to `string` only
Plus, Vue also suggests using **Empty String** to represent "null" classname in its code example
[Vue - Class and Style Bindings - Binding to Arrays](https://vuejs.org/guide/essentials/class-and-style.html#binding-to-arrays)
Thus, sync up the typing `CreateRowClassName` with docs and demos
> docs(data-table): fix type of `row-class-name`

- src/date-picker/src/panel/daterange.tsx
- src/date-picker/src/panel/datetime.tsx
- src/date-picker/src/panel/datetimerange.tsx
I found that this was not fully resolved. https://github.com/TuSimple/naive-ui/issues/2552
and this is your commit https://github.com/TuSimple/naive-ui/commit/ec9546265141bce339f9f45f0dff2d7905d72ba3
It seems that only the first demo was fixed, and others remain.
Or maybe there are other reasons I don't know about， I am not sure.
https://www.naiveui.com/zh-CN/os-theme/components/date-picker
> fix(data-picker):make n-date-panel-date fill all area of all demos

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/badge/demos/enUS/custom-content.demo.vue
- src/badge/src/Badge.tsx
This PR adds a `value` slot to `Badge` so you can even use icons as a badge.
> feat: add `value` slot to `Badge`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/demos/enUS/custom-messages.demo.vue
- src/form/demos/enUS/index.demo-entry.md
- src/form/src/Form.tsx
- src/form/src/FormItem.tsx
- src/form/src/interface.ts
This PR will add a `messages` prop to `Form` so it's possible to redefine the standard messages from `async-validator` (i.e. https://github.com/yiminghe/async-validator/blob/master/src/messages.ts).
> feat: add `messages` prop to `Form`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/steps/src/Step.tsx
This PR will add a status dependent class to the rendered output of `NStep` so it's possible to differentiate the steps' status'.
> feat: add status class to `NStep`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/carousel/demos/enUS/index.demo-entry.md
- src/carousel/demos/enUS/scale.demo.vue
- src/carousel/demos/zhCN/index.demo-entry.md
- src/carousel/demos/zhCN/scale.demo.vue
- src/carousel/src/Carousel.tsx
> feat(carousel): adds css theme variables

- src/dialog/demos/enUS/index.demo-entry.md
The content of the table has only 5 columns but the meta row (the row right below the header. It includes such as "| -- |") had 6 columns.
(This PR has been now properly checkouted from branch `docs` and requesting merge to `docs`)
> Document's table meta row sets wrong number of columns (Re - #2691) 

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/switch/demos/enUS/loading.demo.vue
- src/switch/demos/zhCN/loading.demo.vue
- src/switch/src/styles/index.cssr.ts
> fix(switch): abnormal loading animation when switching state

- src/message/src/MessageProvider.tsx
有时用户会获得 MessageReactive 的实例，希望后续有机会主动销毁此 message。
但是调用 message.destroy 时，可能因为此消息的 duration 时间已经过去了，这时 message.destroy() 会报错。
此时不报错似乎更加符合需求。
User may need MessageReactive instance for closing the message directly.
But when calling message.destroy(), the message might already been hidden because the duration setting.
It seems that calling message.destroy on an hidden message shouldn't throw exception.
```
messageReactive = message.info("3 * 3 * 4 * 4 * ?", {
duration: 3000,
});
// after 3000ms
messageReactive.destroy();  // current behavior: throw exception. expected behavior: fail silently
```
Alternative approach:
1. reveal the show/hide status of the message
2. destroy/hide message also set the messageReactiveInstance's value to null
> fix(message): messageReactive.destroy() shouldn't throw when messageReactiveInstance has already been hidden

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dropdown/src/Dropdown.tsx
修复`:show-arrow="true"`情况下，下拉箭头不显示的问题。
Fixes #2977 
修复前：
修复后：
> fix dropdown arrows render incorrect

- src/tag/demos/enUS/bordered.demo.vue
Fixed `bordered` reference for the tag demo. Not sure if that requires a changelog update.
> fix(tag): missing bordered attribute in demo

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/color-picker/src/ColorInputUnit.tsx
https://www.naiveui.com/zh-CN/os-theme/components/color-picker#basic.vue
手动输入alpha的值 总是为1的问题
发现是没有正确返回小数
> fix(color-picker): fix can't set alpha value correctly by hand

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/button/src/styles/index.cssr.ts
> fix(buttom): fix content placeholder incorrect when displayed as block., closes #3178

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/drawer/src/DrawerBodyWrapper.tsx
> fix(drawer): fix `n-drawer` has log warnings of console when use `show-mask` prop

- src/grid/src/Grid.tsx
Modify the wrong spelling of the variable name. Since there is a problem here, it means that there may be places that are not covered by the test case
> fix(grid): correct spelling

- src/upload/src/UploadFile.tsx
After the upload is done, the image will be transferred to an oss url, which will be stored in the backend database.
And when the users want to review these images on some other day, frontend will fetch those urls from backend and refill the url values in `file.thumbnailUrl`.
In this case, `<UploadFile />` will failed to display thumbnails, because the code can't go into the right code path
Since the thumbnail image src accepts `this.thumbnailUrl || file.thumbnailUrl || file.url`, sure the code path should accept `file.thumbnailUrl` too.
So, add `file.thumbnailUrl`
> fix(upload): accept `file.thumbnailUrl`

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/select/src/Select.tsx
> fix(select): fix select focus loss

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/drawer/src/Drawer.tsx
> fix(drawer): fix `n-drawer`'s warning when using `string` in `default-height` prop

- src/dialog/demos/enUS/index.demo-entry.md
Missmatch between en and cn version. I assume that en is wrong.
> docs(dialog): move style to DialogReactive props (en)

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/selection/src/Selection.tsx
- src/tag/demos/enUS/closable.demo.vue
- src/tag/demos/enUS/index.demo-entry.md
- src/tag/demos/zhCN/closable.demo.vue
- src/tag/demos/zhCN/index.demo-entry.md
- src/tag/src/Tag.tsx
> feat(tag): expose `trigger-click-on-close` prop

- src/loading-bar/tests/LoadingBar.spec.tsx
- src/message/tests/Message.spec.tsx
- src/notification/tests/Notification.spec.tsx
prework of migrate to Vitest
because from Vitest v0.10.0, the callback style of declaring tests is deprecated. 
I rewrite all of them to use async/await functions.
https://vitest.dev/guide/migration.html#migrating-from-jest
> test: done style to async style

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- package.json
Added the `exports` field in package.json.
This field is sometimes used by bundlers to to differentiate `import` from `require`.
> Add `exports` field in package.json for ESM and CommonJS

- src/locales/common/viVN.ts
feat(locales): add vietnamese Transfer, fix typo in vietnamese dateFormat.
> feat(locales): add vietnamese for Transfer, fix typo in dateFormat

- src/timeline/demos/enUS/item-placement.demo.vue
- set value to `right` in `item-placement` demo (consistent with the Chinese version)
---
- `item-placement` demo 的值设为`right`（与中文文档保持一致）
> docs(timeline): set value to `right` in item-placement demo

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/src/DataTable.tsx
- src/data-table/src/TableParts/Body.tsx
- src/data-table/src/interface.ts
- src/data-table/src/styles/index.cssr.ts
- src/data-table/src/use-expand.ts
> feat(data-table): add `expanded-row-remain-sticky` option

- src/transfer/demos/zhCN/index.demo-entry.md
version 2.32.1
Transfer component
The parameter from provided by the api document of the component is still displayed on the Chinese documentc
fix `render-source-label` and `render-target-label`'s doc error
> docs(transfer): fix api describe

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/transfer/demos/enUS/filterable.demo.vue
- src/transfer/demos/enUS/index.demo-entry.md
- src/transfer/demos/zhCN/filterable.demo.vue
- src/transfer/demos/zhCN/index.demo-entry.md
- src/transfer/src/Transfer.tsx
- src/transfer/src/interface.ts
- src/transfer/src/use-transfer-data.ts
- src/transfer/tests/Transfer.spec.ts
> feat(transfer): add `source-filterable` and `target-filterable` props

- src/theme-editor/src/ThemeEditor.tsx
- Added button to expend the ThemeEditor popover (top right of the popover).
- Made the style variables inputs responsive.
> feat(theme-editor): add button to widen popover

- CHANGELOG.zh-CN.md
- src/pagination/src/Pagination.tsx
修复 Pagination 禁用时，快速跳转功能还可使用的问题
> Pagination 禁用时，同时禁用快速跳页功能

- src/tree/src/Tree.tsx
- src/tree/src/styles/index.cssr.ts
fix issue https://github.com/tusen-ai/naive-ui/issues/3561
> Tree content style

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/zhCN/index.demo-entry.md
- src/dialog/src/DialogEnvironment.tsx
> feat(dialog): add `onAfterLeave` in DialogOptions Properties

- scripts/post-build/gen-web-types.js
This PR aims at improving user experience in WebStorm and other JetBrains IDEs. The generated Web Types will now include available documentation and information about slots. Source navigation and links to online documentation are also added.
Here is a screencast of how code completion works with new Web Types:
Please note that some of the features as code completion within slot destructing parameters will be available on in WebStorm 2022.3.
WebStorm works with `.d.ts` files, but the experience is worse than with properly created Web Types. Further improvements to integration between `*.d.ts` and Web Types is expected to come in 2022.3.
close #3675
> docs: improve Web Types generation; include available documentation

- scripts/post-build/gen-web-types.js
This is a follow up to #3691. It fixes issue with default values having back quotes around them.
> docs: improve Web Types generation - remove quotes around default value

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/image/src/ImagePreview.tsx
修复 `n-image` 进行图片预览只可以按住鼠标左键拖拽，关闭 [#3950](https://github.com/tusen-ai/naive-ui/issues/3950)
> fix(image): preview image mouse to drag (#3950)

- src/popover/src/styles/index.cssr.ts
Numbers and English do not wrap when the width limit is exceeded
reproduction：https://codesandbox.io/s/keen-hopper-ebrgdj?file=/src/Demo.vue
> fix(popover): Numbers and English do not wrap when the width limit is exceeded

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/TableParts/Header.tsx
- src/data-table/src/styles/index.cssr.ts
Wrap a `DIV` container around the columns of `n-data-table` to optimize the layout of the filter button.
closes #3853.
> refactor(n-data-table): optimize the layout of filter button

- src/upload/demos/zhCN/index.demo-entry.md
- src/upload/demos/zhCN/on-finish.demo.vue
- src/upload/src/Upload.tsx
在on-finish回调中去获取当前上传成功文件的一些属性
关闭 #3868
> on-finish 中保留 file对象 关闭 #3868

- src/dynamic-input/src/DynamicInput.tsx
When the Create button is pressed on DynamicInput, the onCreate handler is called with the wrong index.
> fix dynamic-input wrong index on create click

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/src/styles/input.cssr.ts
> fix(input): show password icon is offset when use both `password` and `disabled`

- src/drawer/demos/enUS/index.demo-entry.md
- src/drawer/demos/zhCN/index.demo-entry.md
n-drawer 這個prop是無效的
看了一下原碼應該對應`drawerStyle`跟`drawerClass`
[main/src/drawer/src/Drawer.tsx#L111](https://github.com/tusen-ai/naive-ui/blob/96b573ef8c354a2336720b10f9b6891e98dcb1c7/src/drawer/src/Drawer.tsx#L111)
> docs(drawer): Fix wrong prop name

- src/countdown/demos/enUS/index.demo-entry.md
- src/countdown/demos/zhCN/index.demo-entry.md
Countdown 组件 API功能说明文档中的 duration 类型提示有误
> docs(countdown): Type hint error for 'duration'

- src/form/demos/enUS/async.demo.vue
- src/form/demos/zhCN/async.demo.vue
The demo at https://www.naiveui.com/en-US/os-theme/components/form#async.vue seems to aim to validate whether a Chinense phone number is provided in the `Phone` field, but the incorrect regex causes a correct phone number to fail the validation.
> fix: async form validation demo phone number alway invalid

- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/index.demo-entry.md
通过我的一些实验，我注意到复选标记在单选和多选模式下的行为相似。这可能是歧义或文档错误。
> docs(select): Description error for 'show-checkmark'

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/demos/zhCN/cascade.demo.vue
- src/tree/src/TreeNodeCheckbox.tsx
> fix(tree): check all items instead of uncheck them if indeterminate checkbox is clicked

- src/data-table/demos/zhCN/index.demo-entry.md
Fix: #4995 
The English docs is displaying correctly.
The Chinese docs is displaying incorrectly.
> docs(data-table): typo checked-row-keys desc

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/src/Input.tsx
> fix(input): `on-keyup` prop type

- src/input/src/Input.tsx
If use like this:
```vue
<template>
<n-input
@keydown.ctrl.c="handleDownKey"
@keydown.ctrl.a="handleDownKey"
/>
</template>
<script setup lang="ts">
import { NInput } from "naive-ui";
const handleDownKey = () => {
console.log("key down pressed");
};
</script>
```
will throw Error
the reason is the `props.onKeydown` maybe `Array`.
https://codesandbox.io/p/sandbox/blissful-rubin-wz7sfn?file=%2Fsrc%2FApp.vue%3A16%2C1
> fix(Input): Input props onKeydown is Array

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_utils/vue/flatten.ts
- src/space/src/Space.tsx
> fix(space): vnode reuse problem caused by filtering out comment vnodes of slot

- src/_utils/css/color-to-class.ts
- 在n-config-provider组件中设置inline-theme-disabled为true时，以下组件如果使用自定义color，格式为rgba(0,0,0,0.3)
- 导致颜色设置设置不上
- color2Class方法未处理小数点，导致类名无法解析
- tag
- avatar
- badge
- button
- rate
> fix(color2Class):处理rgba中的小数点

- src/avatar/demos/enUS/index.demo-entry.md
The following link does not take to the correct section ID, correct full link should be https://www.naiveui.com/en-US/os-theme/components/avatar#Avatar-Props
> Fixed "Avatar Props" not linking to the correct section

- src/_internal/select-menu/src/SelectMenu.tsx
- src/popselect/src/PopselectPanel.tsx
关于https://github.com/tusen-ai/naive-ui/pull/4719
起因是我也发现和[4700](https://github.com/tusen-ai/naive-ui/issues/4700)相同的问题 但是我找到了这条[2812](https://github.com/tusen-ai/naive-ui/issues/2812)issue 我发现在当时修复此issue的commit中使用的方式为修改Select对SelectMenu传入的onMouseDown事件逻辑 而4700中的修复方式为给empty添加了data-action属性
我查看了所有外部嵌套了SelectMenu的组件 发现只有Select与PopSelectPanel 所以我做了如下修改 我想是不是从外部去修复风险更小些
> refactor: refactor empty slot action then it is an interactive component

- src/avatar/demos/zhCN/index.demo-entry.md
Pretty much the same edit here but for Chinese docs https://github.com/tusen-ai/naive-ui/pull/5180
> Fixed "Avatar Props" not linking to the correct section for Chinese docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/time-picker/src/TimePicker.tsx
> fix(n-time-picker): time picker formatting (format="HH: mm: ss. SSS") preventing modification of milliseconds in the edit box

- src/tabs/src/Tabs.tsx
- src/tabs/src/styles/index.cssr.ts
closes #3910
Just a ugly brute force implementation, for prototyping an idea. The following things need to be checked:
Demo:
> feat(tabs): add animation for segment

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/demos/zhCN/indent.demo.vue
- src/menu/src/use-menu-child.ts
Adjusted the `paddingLeftRef` calculation logic to ensure proper left margin in different scenarios, addressing the issue of content overflow when setting a smaller root-indent in n-menu.
Fixed the calculation of the `::before` pseudo-element's left position, adjusting its default value to match the design expectation and preventing content overflow.
Fixes #5616
> fix(menu): resolve overflow issue with n-menu root-indent (#5616)

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/qr-code/demos/enUS/index.demo-entry.md
- src/qr-code/demos/enUS/type.demo.vue
- src/qr-code/demos/zhCN/index.demo-entry.md
- src/qr-code/demos/zhCN/type.demo.vue
- src/qr-code/src/QrCode.tsx
- src/qr-code/src/qrcodegen.ts
closes https://github.com/tusen-ai/naive-ui/issues/5743.
> feat(n-qr-code): adds `type` prop, Customize rendering output by setting `type`, providing two options: `canvas` and `svg`.

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/upload/demos/enUS/index.demo-entry.md
- src/upload/demos/zhCN/index.demo-entry.md
- src/upload/src/UploadFile.tsx
- src/upload/src/UploadFileList.tsx
- src/upload/src/interface.ts
closes [#5747](https://github.com/tusen-ai/naive-ui/issues/5747)
> feat(n-upload): export the `index` prop of on-remove function

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/date-picker/src/utils.ts
As noted in https://github.com/tusen-ai/naive-ui/issues/5702, the client is getting a UTC timestamp and then getting a locale-based format. In doing so, the month can be off if your UTC offset takes you into another month. In my case, being GMT-8, the timestamp was at 4pm on the final day of the previous month.
Noticed with getMonthString(), but fixing for the others as well just in case.
closes #5702
> fix: get*String() methods for UTC/locale mismatch

- src/locales/common/arDZ.ts
- src/locales/common/csCZ.ts
- src/locales/common/deDE.ts
- src/locales/common/enGB.ts
- src/locales/common/enUS.ts
- src/locales/common/eo.ts
- src/locales/common/esAR.ts
- src/locales/common/etEE.ts
- src/locales/common/faIR.ts
- src/locales/common/frFR.ts
- src/locales/common/idID.ts
- src/locales/common/itIT.ts
- src/locales/common/jaJP.ts
- src/locales/common/koKR.ts
- src/locales/common/nbNO.ts
- src/locales/common/nlNL.ts
- src/locales/common/plPL.ts
- src/locales/common/ptBR.ts
- src/locales/common/ruRU.ts
- src/locales/common/skSK.ts
- src/locales/common/svSE.ts
- src/locales/common/thTH.ts
- src/locales/common/trTR.ts
- src/locales/common/ukUA.ts
- src/locales/common/viVN.ts
- src/locales/common/zhCN.ts
- src/locales/common/zhTW.ts
fix https://github.com/tusen-ai/naive-ui/issues/6069
> fix [Date-Picker] week display

- demo/pages/docs/customize-theme/enUS/index.md
- demo/pages/docs/customize-theme/zhCN/index.md
- volar.d.ts
我认为在 "修改主题" 与 "调整主题"之间，增加上 "获取主题" 会对新手更加有好。
并且通过 useThemeVars 的链接跳转至 "创建适配主题的组件" 一文，让整个阅读理解更加通顺。
> docs(customize-theme): get theme vars

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/bug_report.zh-CN.yml
> chore: 更新 issue template

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/TableParts/Body.tsx
> fix(data-table): multiple expandTrigger with tree data

- src/space/demos/enUS/index.demo-entry.md
Corrected 'compitable' to 'compatibility' and reworded the sentence slightly for better readability in the Space component documentation.
Sorry for the other PR, i hope this one is ok. Thank you for the library, its really good!
> docs(enUS): correct spelling of 'compatible' in demo entry

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tabs/src/TabPane.tsx
修复了n-tabs组件中， tabpane 得tab Slotsts异常
close #6874
> `n-tabs` Fix the type exception of the tab slots in TabPane.

- CHANGELOG.zh-CN.md
- src/data-table/src/DataTable.tsx
- src/data-table/src/styles/index.cssr.ts
close https://github.com/tusen-ai/naive-ui/issues/6521
> fix(data-table): 修复 `n-data-table` 可排序表格背景颜色变量丢失问题

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree-select/src/TreeSelect.tsx
- src/tree/src/Tree.tsx
Add the indent property of the `Tree` component for `TreeSelect` to support tree indentation.
Move the indent prop from `treeProps` to `treeSharedProps`.
为`TreeSelect`添加`Tree`的indent属性以实现树的缩进，indent属性从`treeProps`移动到了`treeSharedProps`
> feat: add indent prop for Tree in TreeSelect

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/anchor/demos/enUS/index.demo-entry.md
- src/anchor/demos/zhCN/index.demo-entry.md
- src/anchor/src/Link.tsx
`n-anchor-link` adds `title` slot
close https://github.com/tusen-ai/naive-ui/issues/6845
> `n-anchor-link` adds `title` slot

- src/checkbox/demos/enUS/index.demo-entry.md
- src/checkbox/demos/zhCN/index.demo-entry.md
原来的文档：
value的值应该是`(string | number)[]`
> docs: fix  CheckboxGroup on-update:value ts  type

- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/ellipsis.demo.vue
- src/tree/demos/zhCN/index.demo-entry.md
- src/tree/src/Tree.tsx
- src/tree/src/styles/index.cssr.ts
增加 ellipsis 省略
试过里面套一个NEllipsis，感觉效果不是很好，这也是为什么我关了又开的原因。。
> feat(tree): add ellipsis
