- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/date-picker/demos/enUS/index.demo-entry.md
- src/date-picker/demos/enUS/ranges.demo.md
- src/date-picker/demos/zhCN/index.demo-entry.md
- src/date-picker/demos/zhCN/ranges.demo.md
- src/date-picker/src/DatePicker.tsx
- src/date-picker/src/interface.ts
- src/date-picker/src/panel/date.tsx
- src/date-picker/src/panel/daterange.tsx
- src/date-picker/src/panel/datetime.tsx
- src/date-picker/src/panel/datetimerange.tsx
- src/date-picker/src/panel/use-dual-calendar.ts
- src/date-picker/src/styles/index.cssr.ts
> feat(date-picker): `ranges` prop

- demo/pages/docs/jsx/enUS/index.md
- demo/pages/docs/jsx/zhCN/index.md
hello! 
I found an error in the JSX document and I'm glad to help fix it.
> docs: Fix document errors in jsx

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popover/src/PopoverBody.tsx
> fix(popover): x, y may not be synced

- README.md
- README.zh-CN.md
- demo/SiteHeader.vue
- demo/pages/docs/common-issues/enUS/index.md
- demo/pages/docs/common-issues/zhCN/index.md
- demo/pages/docs/introduction/enUS/index.md
- demo/pages/docs/introduction/zhCN/index.md
- demo/pages/home/Footer.vue
- demo/pages/home/index.vue
- demo/utils/ComponentDemo.vue
- demo/utils/EditOnGithubHeader.vue
- package.json
> chore: fix cases for GitHub and TypeScript

- demo/pages/home/Footer.vue
docs  xicons link add 'www',to be consistent with other places
> docs: xicons link add 'www'

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/message/src/MessageProvider.tsx
> fix(message): option should be optional

- .gitignore
> chore(.gitignore): update .gitignore file

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dropdown/demos/enUS/basic.demo.md
- src/dropdown/demos/enUS/cascade.demo.md
- src/dropdown/demos/enUS/index.demo-entry.md
- src/dropdown/demos/enUS/trigger.demo.md
- src/dropdown/demos/zhCN/basic.demo.md
- src/dropdown/demos/zhCN/cascade.demo.md
- src/dropdown/demos/zhCN/index.demo-entry.md
- src/dropdown/demos/zhCN/trigger.demo.md
- src/dropdown/src/Dropdown.ts
- src/dropdown/src/DropdownOption.tsx
- src/dropdown/src/styles/index.cssr.ts
- src/dropdown/styles/light.ts
- src/dropdown/tests/Dropdown.spec.ts
> feat(dropdown): add disabled prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/calendar/src/Calendar.tsx
fix https://github.com/TuSimple/naive-ui/issues/49
> fix(calendar): fix calendar date calc error

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/card/src/Card.tsx
- src/card/src/styles/index.cssr.ts
- src/card/styles/light.ts
- src/dropdown/demos/enUS/basic.demo.md
- src/dropdown/demos/enUS/cascade.demo.md
- src/dropdown/demos/enUS/index.demo-entry.md
- src/dropdown/demos/enUS/trigger.demo.md
- src/dropdown/demos/zhCN/basic.demo.md
- src/dropdown/demos/zhCN/cascade.demo.md
- src/dropdown/demos/zhCN/index.demo-entry.md
- src/dropdown/demos/zhCN/trigger.demo.md
- src/dropdown/src/Dropdown.ts
- src/dropdown/src/DropdownOption.tsx
- src/dropdown/src/styles/index.cssr.ts
- src/dropdown/styles/light.ts
- src/dropdown/tests/Dropdown.spec.ts
> chore: merge feat into main

- .gitignore
- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- README.md
- README.zh-CN.md
- demo/SiteHeader.vue
- demo/pages/docs/common-issues/enUS/index.md
- demo/pages/docs/common-issues/zhCN/index.md
- demo/pages/docs/experimental-features/enUS/index.md
- demo/pages/docs/introduction/enUS/index.md
- demo/pages/docs/introduction/zhCN/index.md
- demo/pages/home/Footer.vue
- demo/pages/home/index.vue
- demo/utils/ComponentDemo.vue
- demo/utils/CopyCodeButton.vue
- demo/utils/EditOnGithubHeader.vue
- package.json
- src/calendar/src/Calendar.tsx
- src/input/src/Input.tsx
- src/menu/src/interface.ts
- src/message/src/MessageProvider.tsx
- src/popover/demos/zhCN/index.demo-entry.md
- src/select/demos/enUS/remote-multiple.demo.md
- src/select/demos/enUS/remote.demo.md
- src/select/demos/zhCN/remote-multiple.demo.md
- src/select/demos/zhCN/remote.demo.md
> merge master into feature

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/loading/src/Loading.tsx
- src/_internal/loading/src/styles/index.cssr.ts
- src/_internal/selection/src/Suffix.tsx
- src/button/src/Button.tsx
- src/cascader/src/CascaderOption.tsx
- src/log/src/LogLoader.tsx
- src/message/src/Message.tsx
> fix(spin): animation shifts

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/spin/demos/enUS/index.demo-entry.md
- src/spin/demos/zhCN/index.demo-entry.md
- src/spin/src/Spin.tsx
> feat(spin): `size` prop support number type

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/demos/enUS/basic.demo.md
- src/input-number/demos/enUS/disabled.demo.md
- src/input-number/demos/enUS/index.demo-entry.md
- src/input-number/demos/enUS/min-max.demo.md
- src/input-number/demos/enUS/show-button.demo.md
- src/input-number/demos/enUS/size.demo.md
- src/input-number/demos/enUS/step.demo.md
- src/input-number/demos/enUS/validator.demo.md
- src/input-number/demos/zhCN/basic.demo.md
- src/input-number/demos/zhCN/disabled.demo.md
- src/input-number/demos/zhCN/index.demo-entry.md
- src/input-number/demos/zhCN/min-max.demo.md
- src/input-number/demos/zhCN/show-button.demo.md
- src/input-number/demos/zhCN/size.demo.md
- src/input-number/demos/zhCN/step.demo.md
- src/input-number/demos/zhCN/validator.demo.md
- src/input-number/src/InputNumber.tsx
- src/input-number/tests/InputNumber.spec.ts
> feat: inputNumber add show-button props

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/src/Slider.tsx
- src/slider/src/utils.ts
> fix(slider): prevent default on touchstart to avoid page scrolling

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/color-picker/demos/enUS/index.demo-entry.md
- src/color-picker/demos/zhCN/index.demo-entry.md
- src/color-picker/src/ColorInput.tsx
- src/color-picker/src/ColorPicker.tsx
- src/color-picker/src/utils.ts
- src/color-picker/tests/ColorPicker.spec.tsx
> fix(color-picker): default value doesn't follow modes

- src/notification/demos/enUS/index.demo-entry.md
- src/notification/demos/zhCN/index.demo-entry.md
> docs(notification): fix typo

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/card/src/Card.tsx
- src/card/src/styles/index.cssr.ts
> fix(card): header-style is not applied to header

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dialog/src/DialogProvider.ts
> fix(dialog):add  dialog destroyAll methods

- .github/pull_request_template.md
- src/button/demos/enUS/icon-button.demo.md
- src/button/demos/enUS/index.demo-entry.md
- src/button/demos/zhCN/icon-button.demo.md
- src/button/demos/zhCN/index.demo-entry.md
- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/zhCN/index.demo-entry.md
- src/modal/demos/enUS/mask-closable.demo.md
- src/modal/demos/enUS/preset-confirm-slot.demo.md
- src/modal/demos/enUS/preset-confirm.demo.md
- src/modal/demos/zhCN/mask-closable.demo.md
- src/modal/demos/zhCN/preset-confirm-slot.demo.md
- src/modal/demos/zhCN/preset-confirm.demo.md
> chore: sync main with docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/demos/enUS/horizontal.demo.md
- src/menu/demos/enUS/select.demo.md
- src/menu/demos/zhCN/horizontal.demo.md
- src/menu/demos/zhCN/select.demo.md
- src/menu/src/styles/index.cssr.ts
> feat(menu): supports use `<a />` and `<router-link />` as label

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- package.json
- src/input-number/src/InputNumber.tsx
- src/progress/src/Circle.tsx
- src/progress/src/Line.tsx
- src/progress/src/Progress.tsx
- src/space/src/Space.tsx
- src/version.ts
> chore: sync feat with main

- src/layout/demos/enUS/basic.demo.md
- src/layout/demos/zhCN/basic.demo.md
checkout from docs branch,commit about n-layout-footer contentStyle attribute.
> docs(layout): delete error attribute on n-layout-footer

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/drawer/demos/enUS/closable.demo.md
- src/drawer/demos/enUS/index.demo-entry.md
- src/drawer/demos/zhCN/closable.demo.md
- src/drawer/demos/zhCN/index.demo-entry.md
- src/drawer/src/Drawer.tsx
- src/drawer/src/DrawerContent.tsx
- src/drawer/src/interface.ts
- src/drawer/src/styles/index.cssr.ts
- src/drawer/styles/light.ts
- src/drawer/tests/Drawer.spec.ts
- src/drawer/tests/Drawer.spec.tsx
> feat(drawer-content): closable prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/auto-complete/src/AutoComplete.tsx
> fix(auto-complete): customizing input not working

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/element/demos/enUS/color.demo.md
- src/element/demos/enUS/index.demo-entry.md
- src/element/demos/zhCN/color.demo.md
- src/element/demos/zhCN/index.demo-entry.md
- src/element/src/Element.ts
- src/progress/demos/enUS/color.demo.md
- src/progress/demos/zhCN/color.demo.md
> feat(element): pass `themeVars` to default slot & add `abstract` prop

- src/form/demos/zhCN/custom-rule.demo.md
Fix the sample code error of the document form custom validation rule.
> fix(doc): Update custom-rule.demo.md zh-CN

- src/form/demos/enUS/custom-rule.demo.md
Fix the sample code error of the document form custom validation rule.
> fix(doc): Update custom-rule.demo.md en-US

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- build/loaders/md-renderer.js
- package.json
- src/grid/demos/enUS/index.demo-entry.md
- src/grid/demos/zhCN/index.demo-entry.md
- src/legacy-grid/demos/enUS/index.demo-entry.md
- src/legacy-grid/demos/zhCN/index.demo-entry.md
- src/typography/demos/enUS/index.demo-entry.md
- src/typography/demos/enUS/router-link.demo.md
- src/typography/demos/enUS/tags.demo.md
- src/typography/demos/zhCN/index.demo-entry.md
- src/typography/demos/zhCN/router-link.demo.md
- src/typography/demos/zhCN/tags.demo.md
- src/typography/src/a.tsx
- src/typography/src/create-header.ts
> feat(n-a): remove `to` prop

- .github/workflows/node.js.yml
> ci: codecov

- src/_utils/index.ts
- src/_utils/naive/extract-public-props.ts
- src/_utils/naive/index.ts
- src/dropdown/demos/enUS/cascade.demo.md
- src/dropdown/demos/zhCN/cascade.demo.md
- src/dropdown/src/Dropdown.ts
- src/dropdown/tests/__snapshots__/Dropdown.spec.ts.snap
- src/popover/src/Popover.ts
- src/popover/src/PopoverBody.tsx
- src/popover/src/interface.ts
- src/popover/src/styles/index.cssr.ts
> feat(dropdown): support class

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/demos/enUS/index.demo-entry.md
- src/form/demos/zhCN/index.demo-entry.md
- src/form/src/Form.tsx
- src/form/src/FormItem.tsx
- src/form/src/utils.ts
> feat(form): support require-mark-placement(#171)

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- design-notes/maintaining.md
- src/_internal/select-menu/src/SelectMenu.tsx
- src/dropdown/src/Dropdown.tsx
- src/dropdown/src/styles/index.cssr.ts
- src/dropdown/styles/light.ts
- src/dropdown/tests/__snapshots__/Dropdown.spec.ts.snap
- src/popover/src/PopoverBody.tsx
- src/popselect/demos/enUS/basic.demo.md
- src/popselect/demos/enUS/cancelable.demo.md
- src/popselect/demos/enUS/multiple.demo.md
- src/popselect/demos/enUS/scrollable.demo.md
- src/popselect/demos/enUS/size.demo.md
- src/popselect/demos/zhCN/basic.demo.md
- src/popselect/demos/zhCN/cancelable.demo.md
- src/popselect/demos/zhCN/multiple.demo.md
- src/popselect/demos/zhCN/scrollable.demo.md
- src/popselect/demos/zhCN/size.demo.md
- src/popselect/src/Popselect.tsx
- src/popselect/src/PopselectPanel.tsx
> feat(popselect): support class attr

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/notification/src/styles/index.cssr.ts
> fix(notification): position not correct

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/select-menu/src/SelectGroupHeader.tsx
- src/_internal/select-menu/src/SelectMenu.tsx
- src/_internal/select-menu/src/SelectOption.tsx
- src/_internal/select-menu/src/interface.ts
- src/_internal/selection/src/Selection.tsx
- src/_utils/index.ts
- src/_utils/vue/render.ts
- src/dialog/src/Dialog.tsx
- src/dropdown/src/DropdownGroupHeader.tsx
- src/dropdown/src/DropdownOption.tsx
- src/dropdown/tests/__snapshots__/Dropdown.spec.ts.snap
- src/mention/src/Mention.tsx
- src/menu/src/MenuOption.tsx
- src/menu/src/MenuOptionContent.tsx
- src/menu/src/MenuOptionGroup.tsx
- src/menu/src/use-menu-child-props.ts
- src/message/src/Message.tsx
- src/message/src/message-props.ts
- src/notification/src/Notification.tsx
- src/select/demos/enUS/custom-option.demo.md
- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/custom-option.demo.md
- src/select/demos/zhCN/index.demo-entry.md
- src/select/src/Select.tsx
- src/select/src/interface.ts
- src/tabs/src/Tab.tsx
> feat(select): add render-label prop, option.label supports render function

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popselect/demos/enUS/index.demo-entry.md
- src/popselect/demos/zhCN/index.demo-entry.md
- src/popselect/src/Popselect.tsx
- src/popselect/src/PopselectPanel.tsx
- src/select/demos/enUS/index.demo-entry.md
> feat(popselect): add render-label prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- design-notes/maintaining.md
- src/form/src/Form.tsx
- src/form/src/FormItem.tsx
- src/form/src/utils.ts
- src/form/tests/Form.spec.ts
- src/form/tests/Form.spec.tsx
> fix(form-item): always show require mark

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/src/Tree.tsx
> fix(tree): drag over leaf node causes error

- src/alert/demos/enUS/index.demo-entry.md
- src/date-picker/demos/enUS/index.demo-entry.md
- src/date-picker/demos/zhCN/index.demo-entry.md
> docs: date picker docs

- src/tabs/demos/enUS/index.demo-entry.md
- src/tabs/demos/zhCN/index.demo-entry.md
> fix tab docs error

- src/message/demos/enUS/index.demo-entry.md
- src/message/demos/zhCN/index.demo-entry.md
> docs(message): add use not int setup demo

- src/modal/demos/enUS/index.demo-entry.md
- src/modal/demos/zhCN/index.demo-entry.md
> docs(modal): remove show-mask

- src/alert/tests/Alert.spec.ts
> 增加了一些 Alert 的测试代码

- src/carousel/demos/zhCN/basic.demo.md
> docs(carousel): fix basic title

- src/button/tests/Button.spec.tsx
> test(button): optimization button test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/date-picker/src/DatePicker.tsx
> fix(date-picker): provider pass date-locale not work

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/select-menu/src/SelectGroupHeader.tsx
- src/_internal/select-menu/src/SelectOption.tsx
- src/select/src/interface.ts
- src/select/tests/Select.spec.tsx
> refactor(select): rename option.render => option.renderLabel

- src/descriptions/demos/enUS/index.demo-entry.md
- src/descriptions/demos/zhCN/index.demo-entry.md
> docs: descriptions docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/message/src/use-message.ts
> feat:(message): add useMessage usage link of prerequisite

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/carousel/src/Carousel.tsx
> fix(carousel): fix carousel click triggering button bug

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/src/MenuOption.tsx
ref https://github.com/TuSimple/naive-ui/issues/306
> fix(menu): tooltip content doesn't follow render-label when collapsed

- .gitignore
- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- package.json
- scripts/post-build/gen-web-types.js
- scripts/post-build/index.js
> feat(web-types): add web-types.json

- src/collapse/tests/Collapse.spec.tsx
> test(collapse): add collapse test

- src/input/demos/zhCN/index.demo-entry.md
> feat(input): Improve the documentation

- src/divider/tests/Divider.spec.ts
> test(divider): add divider test

- src/data-table/demos/enUS/ellipsis-tooltip.demo.md
- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/ellipsis-tooltip.demo.md
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/src/TableParts/Body.tsx
- src/ellipsis/src/Ellipsis.tsx
- src/ellipsis/src/styles/index.cssr.ts
- src/menu/demos/enUS/long-label.demo.md
- src/menu/demos/zhCN/long-label.demo.md
> fix(ellipsis): fix ellipsis word

- src/image/demos/zhCN/index.demo-entry.md
> doc(image)

- src/ellipsis/tests/Ellipsis.spec.tsx
> test(ellipsis): add ellipsis test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/carousel/demos/enUS/hover.demo.md
- src/carousel/demos/enUS/index.demo-entry.md
- src/carousel/demos/zhCN/hover.demo.md
- src/carousel/demos/zhCN/index.demo-entry.md
- src/carousel/src/Carousel.tsx
> feat(carousel): add trigger prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/selection/src/Selection.tsx
- src/_internal/selection/src/interface.ts
- src/select/demos/enUS/action.demo.md
- src/select/demos/enUS/basic.demo.md
- src/select/demos/enUS/clearable.demo.md
- src/select/demos/enUS/fallback-option.demo.md
- src/select/demos/enUS/filterable.demo.md
- src/select/demos/enUS/group.demo.md
- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/enUS/max-tag-count.demo.md
- src/select/demos/enUS/multiple.demo.md
- src/select/demos/enUS/render-tag.demo.md
- src/select/demos/enUS/size.demo.md
- src/select/demos/enUS/tag.demo.md
- src/select/demos/zhCN/action.demo.md
- src/select/demos/zhCN/basic.demo.md
- src/select/demos/zhCN/clearable.demo.md
- src/select/demos/zhCN/fallback-option.demo.md
- src/select/demos/zhCN/filterable.demo.md
- src/select/demos/zhCN/group.demo.md
- src/select/demos/zhCN/index.demo-entry.md
- src/select/demos/zhCN/max-tag-count.demo.md
- src/select/demos/zhCN/multiple.demo.md
- src/select/demos/zhCN/render-tag.demo.md
- src/select/demos/zhCN/size.demo.md
- src/select/demos/zhCN/tag.demo.md
- src/select/src/Select.tsx
- src/select/tests/Select.spec.tsx
> feat: select add render-tag prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/loading-bar/src/LoadingBar.tsx
> fix(loading-bar): disappears unexpectly

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/collapse/src/CollapseItem.tsx
> fix: the props of defaultExpandedNames in Collpase fixed

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/loading-bar/index.ts
- `n-loading-bar` 导出 `LoadingBarApiInjection` 类型
> 对外导出 LoadingBarApiInjection

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/upload/src/Upload.tsx
> fix(upload): `multiple=false` doesn't work for drag & drop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/demos/enUS/render-label.demo.md
- src/menu/demos/zhCN/render-label.demo.md
- src/menu/src/Submenu.tsx
> fix(menu): render-label not working for dropdown in collapsed mode

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/selection/src/Selection.tsx
- src/_utils/index.ts
- src/_utils/naive/attribute.ts
- src/_utils/naive/index.ts
- src/anchor/src/Link.tsx
- src/badge/src/Badge.tsx
- src/calendar/src/Calendar.tsx
- src/transfer/src/TransferListItem.tsx
- src/upload/src/UploadFile.tsx
In cases where text is likely to be truncated and ignored, you need a way to see the ignored text.
It's can improves usability for impaired visitors using assisted devices.
| Component | Screenshots |
| --------   | ----- |
| Selection | ![image](https://user-images.githubusercontent.com/37143265/124348575-32d64e80-dc1d-11eb-91d1-ee81ab3a329f.png) |
|  Badge | ![image](https://user-images.githubusercontent.com/37143265/124348361-1259c480-dc1c-11eb-8dcf-99c3bbbd1795.png) |
|  Calendar | ![image](https://user-images.githubusercontent.com/37143265/124348384-403f0900-dc1c-11eb-947b-909c0598629f.png) |
|  Transfer | ![image](https://user-images.githubusercontent.com/37143265/124348426-73819800-dc1c-11eb-9239-884194fbadd5.png) |
|  Anchor | …
> feat(title attribute): Add native title attributes where necessary

- src/gradient-text/tests/GradientText.spec.ts
- src/gradient-text/tests/__snapshots__/GradientText.spec.ts.snap
> test(gradient-text): add gradient-text test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dropdown/demos/enUS/basic.demo.md
- src/dropdown/demos/enUS/cascade.demo.md
- src/dropdown/demos/enUS/placement.demo.md
- src/dropdown/demos/enUS/render-label.demo.md
- src/dropdown/demos/enUS/size.demo.md
- src/dropdown/demos/enUS/trigger.demo.md
- src/dropdown/demos/zhCN/basic.demo.md
- src/dropdown/demos/zhCN/cascade.demo.md
- src/dropdown/demos/zhCN/group-debug.demo.md
- src/dropdown/demos/zhCN/placement.demo.md
- src/dropdown/demos/zhCN/render-label.demo.md
- src/dropdown/demos/zhCN/size.demo.md
- src/dropdown/demos/zhCN/trigger.demo.md
- src/dropdown/src/styles/index.cssr.ts
- src/menu/demos/enUS/render-label.demo.md
- src/menu/demos/zhCN/render-label.demo.md
- src/menu/src/MenuOption.tsx
- src/menu/src/styles/index.cssr.ts
- src/popover/src/Popover.ts
- src/popover/src/PopoverBody.tsx
- src/tooltip/src/Tooltip.ts
> Fix menu tooltip

- src/icon/tests/Icon.spec.ts
- src/icon/tests/__snapshots__/Icon.spec.ts.snap
> test(icon): add NIcon test

- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/zhCN/index.demo-entry.md
> docs: docs dialog

- CHANGELOG.zh-CN.md
- src/popconfirm/src/Popconfirm.ts
> fix: popover internalExtraClass prop type error in popconfirm.

- src/popover/demos/enUS/index.demo-entry.md
- src/popover/demos/zhCN/index.demo-entry.md
> doc(popover)

- src/page-header/tests/PageHeader.spec.tsx
> test(page-header): add NPageHeader test

- src/menu/tests/Menu.spec.ts
- src/menu/tests/__snapshots__/Menu.spec.ts.snap
> test(menu): add menu render-label dropdown test

- src/typography/tests/Typography.spec.ts
- src/typography/tests/__snapshots__/Typography.spec.ts.snap
> test(typography): add typography test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/selection/src/Selection.tsx
- src/_internal/selection/src/styles/index.cssr.ts
- src/select/src/Select.tsx
> fix(select): fix NSelect bug in using custom label

- src/rate/tests/Rate.spec.ts
- src/rate/tests/__snapshots__/Rate.spec.ts.snap
> feat(n-rate): add test

- src/divider/demos/enUS/index.demo-entry.md
- src/divider/demos/zhCN/index.demo-entry.md
> docs: add divider docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/src/Input.tsx
fix [#428](https://github.com/TuSimple/naive-ui/issues/428).
> fix(input): fix clearable position

- src/tree/demos/enUS/basic.demo.md
- src/tree/demos/enUS/cascade.demo.md
- src/tree/demos/enUS/filter.demo.md
- src/tree/demos/enUS/multiple.demo.md
- src/tree/demos/enUS/prefix-and-suffix.demo.md
- src/tree/demos/zhCN/basic.demo.md
- src/tree/demos/zhCN/cascade.demo.md
- src/tree/demos/zhCN/filter.demo.md
- src/tree/demos/zhCN/multiple.demo.md
- src/tree/demos/zhCN/prefix-and-suffix.demo.md
> docs(tree): fix tree demo

- src/drawer/demos/enUS/basic.demo.md
- src/drawer/demos/enUS/index.demo-entry.md
- src/drawer/demos/enUS/target.demo.md
- src/drawer/demos/zhCN/basic.demo.md
- src/drawer/demos/zhCN/index.demo-entry.md
- src/drawer/demos/zhCN/target.demo.md
> docs: add drawer docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/zhCN/index.demo-entry.md
- src/dialog/src/Dialog.tsx
- src/dialog/src/DialogEnvironment.tsx
fixed [420](https://github.com/TuSimple/naive-ui/issues/420).
> feat(dialog): add mask-closable prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/steps/demos/enUS/basic.demo.md
- src/steps/demos/enUS/custom-icon.demo.md
- src/steps/demos/enUS/index.demo-entry.md
- src/steps/demos/enUS/vertical.demo.md
- src/steps/demos/zhCN/basic.demo.md
- src/steps/demos/zhCN/custom-icon.demo.md
- src/steps/demos/zhCN/index.demo-entry.md
- src/steps/demos/zhCN/size.demo.md
- src/steps/demos/zhCN/vertical.demo.md
- src/steps/src/Step.tsx
- src/steps/src/Steps.tsx
- src/steps/tests/Steps.spec.ts
> feat(steps): steps add custom icon

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dialog/src/Dialog.tsx
- src/dialog/src/DialogEnvironment.tsx
- src/dialog/tests/Dialog.spec.ts
- src/dialog/tests/Dialog.spec.tsx
> fix(dialog): dialog call hide error

- src/select/demos/enUS/custom-option.demo.md
- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/custom-option.demo.md
- src/select/demos/zhCN/index.demo-entry.md
> docs(select): 完善选择器组件的文档

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/demos/enUS/index.demo-entry.md
- src/slider/demos/zhCN/index.demo-entry.md
- src/slider/src/Slider.tsx
close https://github.com/TuSimple/naive-ui/issues/389
> feat(slider): add format-tooltip prop

- src/checkbox/tests/Checkbox.spec.ts
> test(checkbox): add checkbox test

- src/dynamic-input/demos/enUS/basic.demo.md
- src/dynamic-input/demos/enUS/custom.demo.md
- src/dynamic-input/demos/enUS/form.demo.md
- src/dynamic-input/demos/enUS/index.demo-entry.md
- src/dynamic-input/demos/enUS/pair.demo.md
- src/dynamic-input/demos/zhCN/basic.demo.md
- src/dynamic-input/demos/zhCN/custom.demo.md
- src/dynamic-input/demos/zhCN/form.demo.md
- src/dynamic-input/demos/zhCN/index.demo-entry.md
- src/dynamic-input/demos/zhCN/pair.demo.md
> docs: add dynamic-input docs

- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/index.demo-entry.md
> docs(select): add select slots docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/upload/demos/enUS/index.demo-entry.md
- src/upload/demos/enUS/on-finish.demo.md
- src/upload/demos/zhCN/index.demo-entry.md
- src/upload/demos/zhCN/on-finish.demo.md
- src/upload/src/Upload.tsx
- src/upload/src/interface.ts
> feat(upload): add event in on-finish callback

- src/table/src/styles/index.cssr.ts
> fix(table): fix css attribute `white-space`

- src/switch/demos/enUS/index.demo-entry.md
- src/switch/demos/zhCN/index.demo-entry.md
> docs(switch): add switch docs

- src/icon/demos/enUS/index.demo-entry.md
- src/icon/demos/zhCN/index.demo-entry.md
> docs(icon): 更新图标组件的说明文档

- src/avatar/demos/enUS/index.demo-entry.md
- src/avatar/demos/zhCN/index.demo-entry.md
- src/image/demos/enUS/index.demo-entry.md
- src/image/demos/zhCN/index.demo-entry.md
> docs: add avatar and image docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tag/src/common-props.ts
> fix(tag): type prop add primary type

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/calendar/demos/enUS/basic.demo.md
- src/calendar/demos/zhCN/basic.demo.md
- src/calendar/src/Calendar.tsx
- src/calendar/tests/Calendar.spec.tsx
> fix(calendar): fix n-calendar's default-value prop cannot be used

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree/demos/enUS/batch-render.demo.md
- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/batch-render.demo.md
- src/tree/demos/zhCN/index.demo-entry.md
- src/tree/src/Tree.tsx
- src/tree/src/TreeNode.tsx
- src/tree/src/TreeNodeContent.tsx
- src/tree/src/interface.ts
- src/tree/tests/Tree.spec.ts
> feat(tree):  `n-tree` add `render-label`, `render-prefix` and `render-suffix` props.

- src/dynamic-tags/demos/enUS/basic.demo.md
- src/dynamic-tags/demos/enUS/form.demo.md
- src/dynamic-tags/demos/enUS/index.demo-entry.md
- src/dynamic-tags/demos/zhCN/basic.demo.md
- src/dynamic-tags/demos/zhCN/form.demo.md
- src/dynamic-tags/demos/zhCN/index.demo-entry.md
- src/tag/demos/enUS/checkable.demo.md
- src/tag/demos/enUS/index.demo-entry.md
- src/tag/demos/zhCN/checkable.demo.md
- src/tag/demos/zhCN/index.demo-entry.md
- src/tag/demos/zhCN/rtl-debug.demo.md
> docs: update tag docs

- src/descriptions/tests/Descriptions.spec.ts
> feat(descriptions): add NDescriptions test

- src/popselect/demos/enUS/index.demo-entry.md
- src/popselect/demos/zhCN/index.demo-entry.md
> docs(popselect): add NPopselect docs

- design-notes/maintaining.md
> feat: update pr checklist

- src/descriptions/tests/Descriptions.spec.ts
> test(descriptions): add NDescriptions slots test

- src/list/tests/List.spec.ts
> test(list): add list test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/mention/demos/enUS/index.demo-entry.md
- src/mention/demos/zhCN/index.demo-entry.md
- src/mention/src/Mention.tsx
> feat: mention add empty slot

- README.md
- README.zh-CN.md
> docs: add Awesome in README

- src/form/demos/enUS/index.demo-entry.md
- src/form/demos/zhCN/index.demo-entry.md
> docs: add form docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/descriptions/src/Descriptions.tsx
> fix: descriptions cannot use v-for render child

- src/dialog/tests/Dialog.spec.tsx
> fix(dialog): dialog test failed

- src/color-picker/demos/enUS/index.demo-entry.md
- src/color-picker/demos/zhCN/alpha.demo.md
- src/color-picker/demos/zhCN/index.demo-entry.md
- src/color-picker/src/ColorPicker.tsx
- src/color-picker/src/utils.ts
- src/color-picker/tests/ColorPicker.spec.tsx
- src/locales/common/enUS.ts
- src/locales/common/zhCN.ts
close: https://github.com/TuSimple/naive-ui/issues/319
The Component add control props to support confirm and cancel button.
> feat(color-picker): color-picker support control

- src/table/demos/enUS/index.demo-entry.md
- src/table/demos/zhCN/index.demo-entry.md
> docs(table): 完善表格组件的说明文档

- src/statistic/demos/enUS/index.demo-entry.md
- src/statistic/demos/zhCN/index.demo-entry.md
> docs(statistic): 完善统计数据组件的说明文档

- src/log/demos/enUS/index.demo-entry.md
- src/log/demos/zhCN/index.demo-entry.md
> docs(log): 完善日志组件的说明文档

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/TableParts/Body.tsx
> fix(n-data-table): rowClassName does not work

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/pagination/src/Pagination.tsx
> fix(data-table): data-table endIndex

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/demos/enUS/index.demo-entry.md
- src/menu/demos/enUS/render-label.demo.md
- src/menu/demos/zhCN/index.demo-entry.md
- src/menu/demos/zhCN/render-label.demo.md
- src/menu/src/Menu.tsx
- src/menu/src/MenuOptionContent.tsx
- src/menu/src/Submenu.tsx
- src/menu/tests/Menu.spec.ts
> feat(menu): n-menu add render-icon prop

- src/pagination/demos/enUS/index.demo-entry.md
- src/pagination/demos/zhCN/index.demo-entry.md
> docs(pagination): 完善分页组件的说明文档

- src/steps/demos/enUS/index.demo-entry.md
- src/steps/demos/zhCN/index.demo-entry.md
> docs(steps): 完善步骤条组件的说明文档

- src/input/demos/enUS/index.demo-entry.md
- src/input/demos/zhCN/index.demo-entry.md
> docs(n-input): add input docs

- src/tabs/demos/enUS/index.demo-entry.md
- src/tabs/demos/enUS/line-debug.demo.md
- src/tabs/demos/zhCN/index.demo-entry.md
- src/tabs/demos/zhCN/line-debug.demo.md
> docs(tabs): 完善标签页组件的说明文档和用例

- src/tree-select/demos/enUS/checkbox.demo.md
- src/tree-select/demos/zhCN/checkbox.demo.md
> docs(treeSelect): fix NTreeSelect checkbox demo

- src/menu/demos/enUS/index.demo-entry.md
- src/menu/demos/zhCN/index.demo-entry.md
> docs(menu): 完善菜单组件的说明文档

- src/time/demos/enUS/index.demo-entry.md
- src/time/demos/zhCN/index.demo-entry.md
> docs(time): 完善时间组件的说明文档

- src/thing/demos/enUS/index.demo-entry.md
- src/thing/demos/zhCN/index.demo-entry.md
> docs(thing): 完善东西组件的说明文档

- src/_utils/vue/omit.ts
> refactor: update omit type

- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
> docs(tree): 完善树组件的说明文档

- src/timeline/demos/enUS/index.demo-entry.md
- src/timeline/demos/zhCN/index.demo-entry.md
> docs(timeline): 完善时间线组件的说明文档

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/carousel/src/styles/index.cssr.ts
close https://github.com/TuSimple/naive-ui/issues/625
> fix(carousel): issue 625

- src/grid/demos/enUS/index.demo-entry.md
- src/grid/demos/zhCN/index.demo-entry.md
> docs(grid): 完善栅格组件的说明文档

- src/message/demos/enUS/index.demo-entry.md
- src/message/demos/zhCN/index.demo-entry.md
> docs(n-message): add message docs

- demo/pages/docs/customize-theme/enUS/index.md
- demo/pages/docs/customize-theme/zhCN/index.md
- demo/pages/docs/i18n/enUS/index.md
- demo/pages/docs/i18n/zhCN/index.md
- demo/routes/routes.js
- demo/store/menu-options.js
> docs: add i18n docs

- src/result/demos/enUS/index.demo-entry.md
- src/result/demos/zhCN/index.demo-entry.md
> docs(result): 完善结果页组件的说明文档

- src/skeleton/demos/enUS/index.demo-entry.md
- src/skeleton/demos/zhCN/index.demo-entry.md
> docs(skeleton): 完善骨架屏组件的说明文档

- src/layout/demos/enUS/index.demo-entry.md
- src/layout/demos/zhCN/index.demo-entry.md
> docs(layout): 完善布局组件的说明文档

- src/space/demos/enUS/index.demo-entry.md
- src/space/demos/zhCN/index.demo-entry.md
> docs(space): 完善间距组件的说明文档

- src/mention/tests/Mention.spec.ts
> test(mention): add mention test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/demos/enUS/disabled.demo.md
- src/slider/demos/enUS/format.demo.md
- src/slider/demos/enUS/index.demo-entry.md
- src/slider/demos/zhCN/disabled.demo.md
- src/slider/demos/zhCN/index.demo-entry.md
- src/slider/src/Slider.tsx
- src/slider/src/styles/index.cssr.ts
- src/slider/styles/dark.ts
- src/slider/styles/light.ts
fix [#641](https://github.com/TuSimple/naive-ui/issues/641)
fix console warning
> fix(slider): prop disabled doesn't work

- src/statistic/tests/Statistic.spec.ts
> feat(statistic): add statistic test

- src/tree-select/demos/enUS/index.demo-entry.md
- src/tree-select/demos/zhCN/index.demo-entry.md
> docs(tree-select): size prop

- src/notification/demos/enUS/index.demo-entry.md
- src/notification/demos/zhCN/index.demo-entry.md
> docs(notification): add notification docs

- CONTRIBUTING.md
> feat: update contribute md

- src/popconfirm/demos/enUS/index.demo-entry.md
- src/popconfirm/demos/zhCN/index.demo-entry.md
> docs(popconfirm): 完善弹出确认组件的说明文档

- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/zhCN/index.demo-entry.md
> docs(dialog): 完善对话框组件的说明文档

- src/progress/demos/enUS/index.demo-entry.md
- src/progress/demos/zhCN/index.demo-entry.md
> docs(progress): 完善进度组件的说明文档

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/descriptions/demos/enUS/index.demo-entry.md
- src/descriptions/demos/zhCN/index.demo-entry.md
- src/descriptions/src/Descriptions.tsx
- src/descriptions/src/DescriptionsItem.ts
> feat(n-descriptions): add label-style, content-style prop

- src/thing/tests/Thing.spec.ts
> test(thing): add NThing test

- src/icon/src/Icon.ts
> refactor(icon): icon optimization props

- src/input-number/demos/enUS/index.demo-entry.md
- src/input-number/demos/zhCN/index.demo-entry.md
> docs(input-number): add input-number docs

- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/index.demo-entry.md
> docs(select): add select docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/message/demos/enUS/index.demo-entry.md
- src/message/demos/zhCN/index.demo-entry.md
- src/message/src/MessageProvider.tsx
> feat(message): add message destroyAll method

- src/timeline/tests/Timeline.spec.ts
> test(NTimeline): add timeline test

- src/image/demos/enUS/index.demo-entry.md
> docs(image): update image enus docs

- src/data-table/demos/enUS/flex-height.demo.md
> docs(data-table): update enus flex-height docs

- src/popover/demos/enUS/index.demo-entry.md
- src/popover/demos/enUS/manual-position.demo.md
- src/popover/demos/zhCN/index.demo-entry.md
- src/popover/demos/zhCN/manual-position.demo.md
> docs(NPopover): update NPopover docs

- src/dropdown/demos/enUS/manual-position.demo.md
- src/dropdown/demos/zhCN/manual-position.demo.md
> docs(NDropdown): update Manually Positioned docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/message/src/MessageProvider.tsx
> fix(message): message destroyAll bug

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/timeline/src/TimelineItem.tsx
- src/timeline/tests/Timeline.spec.ts
> fix(timeline): fix NTimeline header slot

- src/popover/src/Popover.ts
> feat(NPopover): add throwError when manually positioned

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/time-picker/src/TimePicker.tsx
- src/time-picker/src/utils.ts
> feat(NTimePicker): NTimePicker optimization the now button logic

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/selection/src/styles/index.cssr.ts
> fix(select): incorrect when disabled and filterable

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/demos/enUS/ajax-usage.demo.md
- src/data-table/demos/zhCN/ajax-usage.demo.md
- src/data-table/src/use-table-data.ts
- src/pagination/demos/enUS/index.demo-entry.md
- src/pagination/demos/enUS/prefix.demo.md
- src/pagination/demos/zhCN/index.demo-entry.md
- src/pagination/demos/zhCN/prefix.demo.md
- src/pagination/src/Pagination.tsx
- src/pagination/src/interface.ts
> feat(pagination): add total of PaginationInfo

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dynamic-tags/demos/enUS/index.demo-entry.md
- src/dynamic-tags/demos/zhCN/index.demo-entry.md
- src/dynamic-tags/src/DynamicTags.tsx
- src/tag/demos/enUS/index.demo-entry.md
- src/tag/demos/zhCN/index.demo-entry.md
- src/tag/src/Tag.tsx
- src/tag/src/common-props.ts
> feat(tag,dynamic-tags): add color and textColor props

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/upload/src/Upload.tsx
- src/upload/src/UploadFile.tsx
- src/upload/src/interface.ts
- src/upload/src/styles/index.cssr.ts
fix [#668](https://github.com/TuSimple/naive-ui/issues/668).
> fix(upload): operation buttons displayed when has file-list & disabled props

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/pagination/demos/enUS/fast-prev.demo.md
- src/pagination/demos/enUS/index.demo-entry.md
- src/pagination/demos/zhCN/fast-prev.demo.md
- src/pagination/demos/zhCN/index.demo-entry.md
- src/pagination/src/Pagination.tsx
- src/pagination/src/interface.ts
- src/pagination/tests/Pagination.spec.ts
> feat(pagination): add fast-prev and fast-next slots

- src/breadcrumb/tests/Breadcrumb.spec.ts
> test(NBreadcrumb): add test

- src/card/demos/enUS/index.demo-entry.md
- src/card/demos/zhCN/index.demo-entry.md
> docs(card): 完善卡片组件的说明文档

- src/menu/demos/enUS/render-label.demo.md
- src/menu/demos/zhCN/render-label.demo.md
- src/menu/src/MenuOptionContent.tsx
- src/menu/tests/Menu.spec.ts
> feat(NMenu): renderIcon enhanced

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/loading-bar/demos/enUS/basic.demo.md
- src/loading-bar/demos/zhCN/basic.demo.md
- src/loading-bar/src/LoadingBar.tsx
> feat(NLoadingBar): fix finish logic

- src/select/demos/enUS/index.demo-entry.md
- src/select/demos/zhCN/index.demo-entry.md
- src/select/src/Select.tsx
> feat(NSelect): add onClear

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/demos/enUS/index.demo-entry.md
- src/menu/demos/zhCN/index.demo-entry.md
- src/menu/src/Menu.tsx
- src/menu/src/MenuOptionContent.tsx
- src/menu/tests/Menu.spec.ts
> feat(NMenu): add render-extra prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popover/src/Popover.ts
> fix(NDropdown): fix NDropdown click exception when using v-for

- src/collapse/demos/enUS/index.demo-entry.md
- src/collapse/demos/zhCN/index.demo-entry.md
> docs(Collapse): 完善折叠面板组件的说明文档

- src/steps/tests/Steps.spec.ts
> test(steps): add test

- src/avatar/demos/enUS/icon.demo.md
- src/avatar/demos/enUS/name-size.demo.md
- src/avatar/demos/zhCN/icon.demo.md
- src/avatar/demos/zhCN/name-size.demo.md
> docs(avatar): update avatar code with vue3

- src/icon/demos/enUS/basic.demo.md
- src/icon/demos/enUS/depth.demo.md
- src/icon/demos/zhCN/basic.demo.md
- src/icon/demos/zhCN/depth.demo.md
> docs(icon): update icon code docs

- src/button/demos/enUS/color.demo.md
- src/button/demos/enUS/group.demo.md
- src/button/demos/enUS/icon.demo.md
- src/button/demos/enUS/loading.demo.md
- src/button/demos/enUS/shape.demo.md
- src/button/demos/enUS/text.demo.md
- src/button/demos/zhCN/color.demo.md
- src/button/demos/zhCN/debug.demo.md
- src/button/demos/zhCN/group.demo.md
- src/button/demos/zhCN/icon.demo.md
- src/button/demos/zhCN/loading.demo.md
- src/button/demos/zhCN/shape.demo.md
- src/button/demos/zhCN/text.demo.md
> docs(button): update button code docs

- src/auto-complete/demos/enUS/after-select.demo.md
- src/auto-complete/demos/enUS/basic.demo.md
- src/auto-complete/demos/enUS/custom-input.demo.md
- src/auto-complete/demos/enUS/size.demo.md
- src/auto-complete/demos/zhCN/after-select.demo.md
- src/auto-complete/demos/zhCN/basic.demo.md
- src/auto-complete/demos/zhCN/custom-input.demo.md
- src/auto-complete/demos/zhCN/size.demo.md
> docs(autoComplete): update aotoComplete code docs

- src/checkbox/demos/enUS/basic.demo.md
- src/checkbox/demos/enUS/controlled.demo.md
- src/checkbox/demos/enUS/group.demo.md
- src/checkbox/demos/enUS/indeterminate.demo.md
- src/checkbox/demos/zhCN/basic.demo.md
- src/checkbox/demos/zhCN/controlled.demo.md
- src/checkbox/demos/zhCN/group.demo.md
- src/checkbox/demos/zhCN/indeterminate.demo.md
> docs(checkbox): update checkbox code docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/modal/demos/enUS/preset-card.demo.md
- src/modal/demos/zhCN/preset-card.demo.md
- src/modal/src/BodyWrapper.tsx
> fix(modal): cannot add custom classes

- src/divider/demos/zhCN/index.demo-entry.md
> docs(divider): 统一分割线组件的中文说明文档

- src/badge/tests/Badge.spec.ts
> test(badge): add badge test

- src/drawer/demos/enUS/index.demo-entry.md
- src/drawer/demos/enUS/slot.demo.md
- src/drawer/demos/zhCN/index.demo-entry.md
- src/drawer/demos/zhCN/slot.demo.md
> docs(drawer): 增加抽屉组件对插槽使用的用例

- src/result/tests/Result.spec.ts
- src/result/tests/__snapshots__/Result.spec.ts.snap
> test(NResult): add test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/demos/enUS/index.demo-entry.md
- src/form/demos/zhCN/index.demo-entry.md
- src/form/index.ts
- src/form/src/interface.ts
> feat(form): export ValidationError

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/button/demos/enUS/index.demo-entry.md
- src/button/demos/zhCN/index.demo-entry.md
- src/button/src/Button.tsx
- src/button/tests/Button.spec.tsx
> feat(NButton): add text-color prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/progress/src/Circle.tsx
- src/progress/src/Line.tsx
- src/progress/src/MultipleCircle.tsx
- src/progress/src/Progress.tsx
- src/progress/tests/Progress.spec.ts
> fix(NProgress): fix percentage prop exception in default

- src/dropdown/demos/enUS/icon.demo.md
- src/dropdown/demos/enUS/index.demo-entry.md
- src/dropdown/demos/zhCN/icon.demo.md
- src/dropdown/demos/zhCN/index.demo-entry.md
> docs(dropdown): 下拉菜单组件增加针对图标使用的用例

- src/progress/tests/Progress.spec.ts
> test(NProgress): add test

- src/input/demos/enUS/basic.demo.md
- src/input/demos/enUS/icon.demo.md
- src/input/demos/enUS/input-group.demo.md
- src/input/demos/zhCN/basic.demo.md
- src/input/demos/zhCN/icon-debug.demo.md
- src/input/demos/zhCN/icon.demo.md
- src/input/demos/zhCN/input-group.demo.md
> docs(input): update input code docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/selection/src/Selection.tsx
- src/select/demos/enUS/multiple.demo.md
- src/select/demos/zhCN/multiple.demo.md
> fix(select): tag should hide close icon when option is disabled

- src/skeleton/tests/Skeleton.spec.tsx
- src/skeleton/tests/__snapshots__/Skeleton.spec.tsx.snap
> test(NSkeleton): add test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popconfirm/demos/enUS/actions.demo.md
- src/popconfirm/demos/enUS/index.demo-entry.md
- src/popconfirm/demos/zhCN/actions.demo.md
- src/popconfirm/demos/zhCN/index.demo-entry.md
- src/popconfirm/src/Popconfirm.ts
- src/popconfirm/src/PopconfirmPanel.tsx
> feat(popconfirm): add actions prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/src/styles/index.cssr.ts
> fix(menu): click menu show background on mobile

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree-select/demos/enUS/index.demo-entry.md
- src/tree-select/demos/zhCN/debug.demo.md
- src/tree-select/demos/zhCN/index.demo-entry.md
- src/tree-select/src/TreeSelect.tsx
- src/tree-select/src/interface.ts
- src/tree-select/src/utils.ts
- src/tree-select/tests/TreeSelect.spec.ts
closes: https://github.com/TuSimple/naive-ui/issues/623
> feat: treeSelect support showPath

- src/message/tests/Message.spec.tsx
> test(message): add message provider closable test

- src/spin/tests/Spin.spec.ts
- src/spin/tests/__snapshots__/Spin.spec.ts.snap
> test(spin): add spin test

- src/result/tests/Result.spec.ts
> test(result): add result statue test

- src/layout/tests/Layout.spec.ts
> test(NLayout): add test

- src/icon/src/Icon.ts
> fix: duplicate attrs

- src/layout/tests/Layout.spec.ts
- src/layout/tests/__snapshots__/Layout.spec.ts.snap
> test(layout): update test

- package.json
- src/data-table/tests/DataTable.spec.tsx
- src/input/src/Input.tsx
> test(data-table): add itemCount test case

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/demos/enUS/render-label.demo.md
- src/menu/demos/zhCN/render-label.demo.md
- src/menu/src/MenuOptionContent.tsx
> fix(menu): renderIcon render error when return true

- src/grid/tests/Grid.spec.tsx
> test(NGrid): add test

- src/_utils/tests/Utils.spec.ts
> test(utils): add utils color test

- src/element/tests/Element.spec.ts
> test(element): add element test case

- package.json
- src/form/src/Form.tsx
- src/form/src/FormItem.tsx
- src/form/src/interface.ts
> type(Form): update async-validator

- src/_utils/tests/Utils.spec.ts
> test(utils): add css test

- src/_utils/tests/Utils.spec.ts
> test(utils): add naive's getTitleAttribute test

- src/locales/common/ruRU.ts
> feat(locale): add Ru locale

- src/_utils/tests/Utils.spec.ts
> feat(utils): update utils naive test

- src/config-provider/demos/enUS/language.demo.md
- src/config-provider/demos/enUS/namespace.demo.md
- src/config-provider/demos/enUS/os-theme.demo.md
- src/config-provider/demos/enUS/theme.demo.md
- src/config-provider/demos/zhCN/index.demo-entry.md
- src/config-provider/demos/zhCN/language.demo.md
- src/config-provider/demos/zhCN/namespace.demo.md
- src/config-provider/demos/zhCN/os-theme.demo.md
- src/config-provider/demos/zhCN/theme.demo.md
> docs(config-provider): 完善文档中的用例

- src/spin/tests/Spin.spec.ts
- src/spin/tests/__snapshots__/Spin.spec.ts.snap
> test(spin): add test case

- src/switch/tests/Switch.spec.ts
> test(switch): add switch test case

- src/_utils/tests/Utils.spec.ts
> test(utils): add utils test

- src/grid/demos/enUS/collapse.demo.md
- src/grid/demos/zhCN/collapse.demo.md
- src/grid/demos/zhCN/index.demo-entry.md
> docs(grid): 更改栅格组件文档的用例

- src/_utils/tests/Utils.spec.ts
> test(utils): add test

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
> docs(NDataTable): update n-data-table docs

- src/message/src/Message.tsx
> feat(message): 增加一个 class (#880)

- src/_utils/tests/Utils.spec.ts
> test(utils): update utils vue test

- src/tooltip/demos/enUS/trigger.demo.md
- src/tooltip/demos/zhCN/trigger.demo.md
> docs(tooltip): 完善文档中的用例

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/demos/enUS/basic.demo.md
- src/input-number/demos/enUS/index.demo-entry.md
- src/input-number/demos/zhCN/basic.demo.md
- src/input-number/demos/zhCN/index.demo-entry.md
- src/input-number/src/InputNumber.tsx
> feat(NInputNumber): add clearable prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_utils/index.ts
- src/_utils/naive/index.ts
- src/_utils/naive/mutable.ts
- src/notification/src/NotificationEnvironment.tsx
- src/notification/src/NotificationProvider.tsx
- src/notification/tests/Notification.spec.ts
- src/notification/tests/Notification.spec.tsx
- src/select/tests/Select.spec.tsx
> fix(notification): NotificationReactive cannot write

- src/_utils/tests/Utils.spec.ts
> test(utils): update vue test

- src/spin/demos/enUS/wrap.demo.md
- src/spin/demos/zhCN/wrap.demo.md
> docs(spin): Update vue2 API to vue3

- src/dropdown/demos/enUS/arrow.demo.md
- src/dropdown/demos/enUS/basic.demo.md
- src/dropdown/demos/enUS/batch-render.demo.md
- src/dropdown/demos/enUS/cascade.demo.md
- src/dropdown/demos/enUS/icon.demo.md
- src/dropdown/demos/enUS/index.demo-entry.md
- src/dropdown/demos/enUS/manual-position.demo.md
- src/dropdown/demos/enUS/placement.demo.md
- src/dropdown/demos/enUS/size.demo.md
- src/dropdown/demos/enUS/trigger.demo.md
- src/ellipsis/demos/enUS/custom-tooltip.demo.md
- src/ellipsis/demos/enUS/index.demo-entry.md
- src/ellipsis/demos/enUS/line-clamp.demo.md
- src/gradient-text/demos/enUS/basic.demo.md
- src/gradient-text/demos/enUS/custom.demo.md
- src/gradient-text/demos/enUS/index.demo-entry.md
- src/gradient-text/demos/enUS/size.demo.md
- src/icon/demos/enUS/custom-icon.demo.md
- src/icon/demos/enUS/depth.demo.md
- src/icon/demos/enUS/index.demo-entry.md
> Docs(NIcon, NEllipsis, NDropdown, NGradientText) EN Wording

- src/drawer/tests/Drawer.spec.tsx
> test(NDrawer): add test for placement

- src/page-header/demos/enUS/basic.demo.md
- src/page-header/demos/enUS/index.demo-entry.md
- src/tag/demos/enUS/index.demo-entry.md
- src/typography/demos/enUS/header.demo.md
- src/typography/demos/enUS/index.demo-entry.md
- src/typography/demos/enUS/router-link.demo.md
- src/typography/demos/enUS/tags.demo.md
- src/typography/demos/enUS/text.demo.md
Docs(NPageHeader, NTag, NTypography)
> Docs(NPageHeader, NTag, NTypography)

- src/drawer/tests/Drawer.spec.tsx
> test(NDrawer): add show/on-update:show/mask-closable props test

- src/popselect/demos/enUS/basic.demo.md
- src/popselect/demos/enUS/cancelable.demo.md
- src/popselect/demos/enUS/multiple.demo.md
- src/popselect/demos/enUS/scrollable.demo.md
- src/popselect/demos/enUS/size.demo.md
- src/popselect/demos/zhCN/basic.demo.md
- src/popselect/demos/zhCN/cancelable.demo.md
- src/popselect/demos/zhCN/multiple.demo.md
- src/popselect/demos/zhCN/scrollable.demo.md
- src/popselect/demos/zhCN/size.demo.md
> docs(popselect): 将弹出选择组件的options api更改为composition api

- src/auto-complete/demos/enUS/after-select.demo.md
- src/auto-complete/demos/enUS/custom-input.demo.md
- src/auto-complete/demos/enUS/index.demo-entry.md
- src/cascader/demos/enUS/action.demo.md
- src/cascader/demos/enUS/index.demo-entry.md
- src/cascader/demos/enUS/size.demo.md
- src/cascader/demos/enUS/virtual.demo.md
- src/checkbox/demos/enUS/grid.demo.md
- src/checkbox/demos/enUS/index.demo-entry.md
- src/color-picker/demos/enUS/alpha.demo.md
- src/color-picker/demos/enUS/basic.demo.md
- src/color-picker/demos/enUS/form.demo.md
- src/color-picker/demos/enUS/index.demo-entry.md
- src/color-picker/demos/enUS/modes.demo.md
> Docs (NAutoComplete, NCascader, NColorPicker, NCheckbox)

- src/popover/demos/enUS/manual-position.demo.md
- src/popover/demos/enUS/placement.demo.md
- src/popover/demos/enUS/trigger.demo.md
- src/popover/demos/zhCN/manual-position.demo.md
- src/popover/demos/zhCN/placement.demo.md
- src/popover/demos/zhCN/trigger.demo.md
> docs(popover): 将弹出信息组件的options api更改为composition api

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/image/src/ImagePreview.tsx
> fix(image): Initialize rotate before switching, closes #921

- src/progress/demos/enUS/circle.demo.md
- src/progress/demos/enUS/line.demo.md
- src/progress/demos/enUS/multiple-circle.demo.md
- src/progress/demos/zhCN/circle.demo.md
- src/progress/demos/zhCN/line.demo.md
- src/progress/demos/zhCN/multiple-circle.demo.md
> docs(progress): 将options api升级为composition api

- src/tree-select/tests/TreeSelect.spec.ts
> test(tree-select): add tree-select test

- src/date-picker/demos/enUS/index.demo-entry.md
- src/dynamic-input/demos/enUS/basic.demo.md
- src/dynamic-input/demos/enUS/index.demo-entry.md
> Docs(DatePicker, DynamicInput) English fixes

- src/modal/tests/Modal.spec.ts
- src/modal/tests/Modal.spec.tsx
> test(modal): add modal test

- .github/workflows/sync-gitee.yml
> feat(action): add sync-gitee action

- src/slider/tests/Slider.spec.ts
> test(slider): add test

- src/popconfirm/demos/enUS/custom-action.demo.md
- src/popconfirm/demos/enUS/custom-icon.demo.md
- src/popconfirm/demos/zhCN/custom-action.demo.md
- src/popconfirm/demos/zhCN/custom-icon.demo.md
> docs(popconfirm): 将弹出确认组件的options api更改为composition api

- src/notification/demos/enUS/index.demo-entry.md
- src/notification/demos/zhCN/index.demo-entry.md
> docs(notification): 将通知组件的options api更改为composition api

- src/modal/demos/enUS/basic.demo.md
- src/modal/demos/enUS/controlled.demo.md
- src/modal/demos/enUS/custom-position.demo.md
- src/modal/demos/enUS/mask-closable.demo.md
- src/modal/demos/enUS/preset-card.demo.md
- src/modal/demos/enUS/preset-confirm-slot.demo.md
- src/modal/demos/enUS/preset-confirm.demo.md
- src/modal/demos/zhCN/basic.demo.md
- src/modal/demos/zhCN/controlled.demo.md
- src/modal/demos/zhCN/custom-position.demo.md
- src/modal/demos/zhCN/mask-closable.demo.md
- src/modal/demos/zhCN/preset-card.demo.md
- src/modal/demos/zhCN/preset-confirm-slot.demo.md
- src/modal/demos/zhCN/preset-confirm.demo.md
> docs(modal): 将模态框组件的options api更改为composition api

- src/select/tests/Select.spec.tsx
> test(select): add test

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
> docs(data-table): 更改数据表格中single-column和single-line的说明，减少对使用者造成的歧义

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dynamic-tags/demos/enUS/index.demo-entry.md
- src/dynamic-tags/demos/enUS/slot.demo.md
- src/dynamic-tags/demos/zhCN/index.demo-entry.md
- src/dynamic-tags/demos/zhCN/slot.demo.md
- src/dynamic-tags/src/DynamicTags.tsx
> feat(dynamic-tags): add input slot.

- src/dialog/demos/enUS/action.demo.md
- src/dialog/demos/enUS/async.demo.md
- src/dialog/demos/enUS/basic.demo.md
- src/dialog/demos/enUS/index.demo-entry.md
- src/dialog/demos/enUS/mask.demo.md
- src/dialog/demos/enUS/use-component.demo.md
- src/dialog/demos/zhCN/action.demo.md
- src/dialog/demos/zhCN/async.demo.md
- src/dialog/demos/zhCN/basic.demo.md
- src/dialog/demos/zhCN/index.demo-entry.md
- src/dialog/demos/zhCN/mask.demo.md
- src/dialog/demos/zhCN/use-component.demo.md
> docs(dialog): 将对话框组件的示例更改为composition api

- src/dynamic-tags/demos/enUS/index.demo-entry.md
- src/dynamic-tags/demos/enUS/slot.demo.md
- src/form/demos/enUS/async.demo.md
- src/form/demos/enUS/custom-rule.demo.md
- src/form/demos/enUS/custom-validation.demo.md
- src/form/demos/enUS/index.demo-entry.md
- src/form/demos/enUS/inline.demo.md
- src/form/demos/enUS/item-only.demo.md
- src/form/demos/enUS/required-mark-debug.demo.md
- src/form/demos/enUS/show-label.demo.md
- src/form/demos/enUS/top.demo.md
> Docs(NDynamicTags, NForms)

- src/ellipsis/tests/Ellipsis.spec.tsx
> test(ellipsis): add test case

- src/space/src/Space.tsx
- src/space/tests/Space.spec.tsx
- src/space/tests/__snapshots__/Space.spec.tsx.snap
> test(space): add test case

- README.zh-CN.md
> docs: add recruit

- src/popconfirm/tests/Popconfirm.spec.ts
> test(popconfirm): add test

- src/breadcrumb/demos/enUS/basic.demo.md
- src/breadcrumb/demos/enUS/separator-per-item.demo.md
- src/breadcrumb/demos/enUS/separator.demo.md
- src/breadcrumb/demos/zhCN/basic.demo.md
- src/breadcrumb/demos/zhCN/separator-per-item.demo.md
- src/breadcrumb/demos/zhCN/separator.demo.md
> docs(breadcrumb): 将面包屑组件的用例升级为composition api

- src/loading-bar/demos/enUS/basic.demo.md
- src/loading-bar/demos/enUS/index.demo-entry.md
- src/loading-bar/demos/zhCN/basic.demo.md
- src/loading-bar/demos/zhCN/index.demo-entry.md
> docs(loading-bar): 将加载条组件的用例升级为composition api

- demo/routes/router.js
- demo/store/index.js
- index.html
> docs(site): add distinct title for each documentation page

- src/switch/demos/enUS/basic.demo.md
- src/switch/demos/zhCN/basic.demo.md
> docs: update switch docs

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/zhCN/index.demo-entry.md
> docs(data-table): add async usage at top

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/cascader/src/Cascader.tsx
> fix(cascader):fixed handleDeleteOption. the tree option is not updated

- src/log/demos/enUS/debug.demo.md
- src/log/demos/enUS/highlight.demo.md
- src/log/demos/enUS/index.demo-entry.md
- src/log/demos/enUS/loading.demo.md
- src/log/demos/zhCN/debug.demo.md
- src/log/demos/zhCN/highlight.demo.md
- src/log/demos/zhCN/index.demo-entry.md
- src/log/demos/zhCN/loading.demo.md
> docs(log): Upgrade the use case of log component to Composition API

- src/code/tests/Code.spec.ts
> test(code): add code test case

- src/time/demos/enUS/basic.demo.md
- src/time/demos/enUS/type.demo.md
- src/time/demos/enUS/unix.demo.md
- src/time/demos/zhCN/basic.demo.md
- src/time/demos/zhCN/type.demo.md
- src/time/demos/zhCN/unix.demo.md
> docs(time): Upgrade the use case of time component to Composition API

- src/thing/demos/enUS/basic.demo.md
- src/thing/demos/enUS/indent.demo.md
- src/thing/demos/zhCN/basic.demo.md
- src/thing/demos/zhCN/indent.demo.md
> docs(thing): Upgrade the use case of thing component to Composition API

- src/progress/src/Line.tsx
- src/progress/tests/Progress.spec.ts
> test(progress): add some test case

- src/tree/demos/enUS/async.demo.md
- src/tree/demos/enUS/drag-drop.demo.md
- src/tree/demos/zhCN/async.demo.md
- src/tree/demos/zhCN/drag-drop.demo.md
> docs(tree): Upgrade the use case of tree component to Composition API

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- package.json
- src/tree-select/demos/enUS/custom-field.demo.md
- src/tree-select/demos/enUS/index.demo-entry.md
- src/tree-select/demos/zhCN/custom-field.demo.md
- src/tree-select/demos/zhCN/index.demo-entry.md
- src/tree-select/src/TreeSelect.tsx
- src/tree/demos/enUS/custom-field.demo.md
- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/custom-field.demo.md
- src/tree/demos/zhCN/index.demo-entry.md
- src/tree/src/Tree.tsx
ref [#42](https://github.com/07akioni/treemate/pull/42)
> feat(tree&tree-select): add children-field prop

- src/space/demos/enUS/index.demo-entry.md
- src/space/demos/zhCN/index.demo-entry.md
> docs(space): update space docs

- src/code/demos/enUS/basic.demo.md
- src/code/demos/enUS/index.demo-entry.md
- src/code/demos/zhCN/basic.demo.md
- src/code/demos/zhCN/index.demo-entry.md
> docs(code): Upgrade the use case of code component to Composition API

- src/cascader/tests/Cascader.spec.ts
> test(cascader): update test

- src/steps/tests/Steps.spec.ts
> test(steps): add some test case

- src/message/demos/enUS/placement.demo.md
- src/message/demos/zhCN/placement.demo.md
> feat(message): Simplify the demo code

- src/cascader/demos/enUS/action.demo.md
- src/cascader/demos/enUS/multiple-lazy.demo.md
- src/cascader/demos/enUS/multiple.demo.md
- src/cascader/demos/enUS/single-lazy.demo.md
- src/cascader/demos/enUS/single.demo.md
- src/cascader/demos/enUS/size.demo.md
- src/cascader/demos/enUS/virtual.demo.md
- src/cascader/demos/zhCN/action.demo.md
- src/cascader/demos/zhCN/multiple-lazy.demo.md
- src/cascader/demos/zhCN/multiple.demo.md
- src/cascader/demos/zhCN/single-lazy.demo.md
- src/cascader/demos/zhCN/single.demo.md
- src/cascader/demos/zhCN/size.demo.md
- src/cascader/demos/zhCN/virtual.demo.md
> docs(cascader): update demo

- src/code/demos/enUS/index.demo-entry.md
- src/code/demos/zhCN/index.demo-entry.md
> docs(code): Basic usage Update Newest import hljs Manner

- src/checkbox/demos/enUS/index.demo-entry.md
- src/checkbox/demos/zhCN/index.demo-entry.md
> docs(checkbox): add size prop

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree-select/src/TreeSelect.tsx
> Fix tree show path

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- package.json
- src/cascader/src/Cascader.tsx
- src/cascader/src/interface.ts
- src/cascader/tests/Cascader.spec.ts
- src/data-table/src/TableParts/Body.tsx
- src/version.ts
> chore: fixed type error caused by vue

- src/gradient-text/tests/GradientText.spec.ts
- src/image/tests/Image.spec.tsx
> test(gradient-test & image): Increase test coverage

- src/radio/demos/enUS/basic.demo.md
- src/radio/demos/enUS/button-group.demo.md
- src/radio/demos/enUS/size.demo.md
- src/radio/demos/zhCN/basic.demo.md
- src/radio/demos/zhCN/button-group.demo.md
- src/radio/demos/zhCN/size.demo.md
> docs(radio): Upgrade the use case of radio component to Composition API

- src/form/demos/enUS/custom-validation.demo.md
- src/form/demos/zhCN/custom-validation.demo.md
> docs(form): Upgrade the use case of form component to Composition API

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/dialog/src/DialogEnvironment.tsx
- src/dialog/src/DialogProvider.ts
- src/dialog/tests/Dialog.spec.tsx
> feat: add style option

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/steps/src/Steps.tsx
> fix(step): fix steps doesn't work with v-for children

- demo/pages/docs/usage-sfc/enUS/index.md
- demo/pages/docs/usage-sfc/zhCN/index.md
> docs(usage-sfc): Upgrade the use case of usage-sfc to Composition API

- demo/pages/docs/theme/enUS/element.demo.md
- demo/pages/docs/theme/enUS/provide-theme.demo.md
- demo/pages/docs/theme/zhCN/element.demo.md
- demo/pages/docs/theme/zhCN/provide-theme.demo.md
> docs(theme): Upgrade the use case of theme to Composition API

- src/time/tests/Time.spec.ts
> test(time): Add time component test

- src/rate/tests/Rate.spec.ts
> test(rate): add some test case

- src/time-picker/tests/TimePicker.spec.ts
> test(time-picker): update test

- src/affix/tests/Affix.spec.ts
> test(affix): Add affix component test

- src/loading-bar/tests/LoadingBar.spec.ts
- src/loading-bar/tests/LoadingBar.spec.tsx
> test(loading-bar): add loadingBar test case

- src/anchor/tests/Anchor.spec.ts
> test(anchor): Update anchor component test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/cascader/demos/enUS/index.demo-entry.md
- src/cascader/demos/zhCN/index.demo-entry.md
- src/cascader/src/Cascader.tsx
- src/cascader/src/interface.ts
> feat(cascader): `n-cascader`'s `on-update:value` prop add option info

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/select/src/Select.tsx
> fix(n-select): focus input when closing tag with filterable

- src/input/tests/Input.spec.tsx
> test(input): update test

- src/button/tests/Button.spec.tsx
> test(button): optimization

- src/back-top/tests/BackTop.spec.ts
> test(backtop): Add backtop component test

- src/table/tests/Table.spec.ts
> test(table): Add table component test

- src/upload/tests/Upload.spec.ts
> test(upload): add test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/src/InputNumber.tsx
> feat(n-input-number): add `readonly`  prop

- src/data-table/tests/DataTable.spec.tsx
> test(data-table): add test

- src/data-table/tests/DataTable.spec.tsx
> test(data-table): update test

- src/tree/tests/Tree.spec.ts
> test(tree): Update tree component test

- src/dynamic-input/tests/DynamicInput.spec.ts
> test(dynamic-input): Add dynamic-input component test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/DataTable.tsx
- src/data-table/src/use-group-header.ts
> fix(data-table): ellipsis ellipsis not show when last column not set ellipsis 

- src/cascader/tests/Cascader.spec.ts
> test(cascader): Update cascader component test

- src/popselect/tests/Popselect.spec.ts
> test(popselect): Add popselect component test

- src/ellipsis/demos/enUS/index.demo-entry.md
> Update index.demo-entry.md, ellipse doc typo fix

- src/menu/demos/enUS/index.demo-entry.md
- src/menu/demos/enUS/router-link.demo.md
- src/menu/demos/enUS/select.demo.md
- src/menu/demos/zhCN/index.demo-entry.md
- src/menu/demos/zhCN/router-link.demo.md
- src/menu/demos/zhCN/select.demo.md
> docs(menu): update router-link usage

- src/popselect/tests/Popselect.spec.ts
> test(popselect): Update popselect component test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/styles/form-item.cssr.ts
https://codesandbox.io/s/elastic-rain-0ml7n?file=/src/Demo.vue
> fix(n-form-item):  too long content affects formItem width

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/date-picker/src/DatePicker.tsx
- src/date-picker/src/panel/date.tsx
> fix: date-picker date action validate error

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/tree-select/src/TreeSelect.tsx
- src/tree/demos/enUS/index.demo-entry.md
- src/tree/demos/zhCN/index.demo-entry.md
- src/tree/src/Tree.tsx
> feat(n-tree): n-tree's on-update prop add option info.

- src/drawer/tests/Drawer.spec.tsx
> test(drawer): Update drawer component test

- package.json
> chore: restore missing dev script

- src/dynamic-input/tests/DynamicInput.spec.ts
> test(dynamicInput): Update dynamicInput component test

- src/affix/tests/Affix.spec.ts
> test(affix): Update affix component test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/upload/src/Upload.tsx
> fix(n-upload): export openFileDialog method

- demo/pages/docs/community/enUS/index.md
- demo/pages/docs/community/zhCN/index.md
- demo/routes/routes.js
- demo/store/menu-options.js
> docs: add Third-Party Libraries

- .github/workflows/node.js.yml
- package.json
set `NODE_OPTIONS=--unhandled-rejections=warn` to add node 16 test
> fix(ci): set NODE_OPTIONS=--unhandled-rejections=warn

- src/tabs/tests/Tabs.spec.tsx
> test(tabs): Update tabs component test

- src/time/tests/Time.spec.ts
> test(time): fix error

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/src/Menu.tsx
- src/menu/tests/Menu.spec.tsx
> fix(n-menu): defaultExpandedKeys use watchEffect initialize

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/grid/src/Grid.tsx
- src/grid/tests/Grid.spec.tsx
> fix(gird): suffix gridItem`s span does not work when collapsed

- demo/pages/home/Footer.vue
> docs: update footer libraries

- src/radio/tests/Radio.spec.ts
> test(radio): update test

- src/modal/demos/enUS/index.demo-entry.md
- src/modal/demos/zhCN/index.demo-entry.md
> docs(modal): add `to` prop

- demo/pages/docs/ssr/zhCN/index.md
> docs(ssr): update srr zhCN index.md

- demo/pages/docs/community/enUS/index.md
- demo/pages/docs/community/zhCN/index.md
> docs(community): add a vue admin template

- demo/pages/docs/customize-theme/enUS/index.md
- demo/pages/docs/customize-theme/zhCN/index.md
- src/_utils/naive/extract-public-props.ts
> docs(theme): complete theme docs

- src/pagination/demos/enUS/index.demo-entry.md
- src/pagination/demos/enUS/page-size-option.demo.md
- src/pagination/demos/zhCN/index.demo-entry.md
- src/pagination/demos/zhCN/page-size-option.demo.md
- src/pagination/index.ts
- src/pagination/src/Pagination.tsx
- src/pagination/src/interface.ts
> feat(pagination): update pageSizes type

- src/config-provider/demos/zhCN/namespace.demo.md
> fix: 全局配置描述

- src/radio/demos/zhCN/index.demo-entry.md
> docs(radio): update on-update:checked in zhCN

- src/slider/tests/Slider.spec.ts
> test(slider): update test

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/enUS/virtual.demo.md
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/demos/zhCN/virtual.demo.md
> docs(data-table): add `virtual-scroll` prop tip

- src/log/tests/Log.spec.ts
> test(log): update test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/demos/enUS/index.demo-entry.md
- src/slider/demos/enUS/restrict-selectable-values.demo.md
- src/slider/demos/zhCN/index.demo-entry.md
- src/slider/demos/zhCN/restrict-selectable-values.demo.md
- src/slider/src/Slider.tsx
- src/slider/tests/Slider.spec.ts
`step` prop support `mark` option.
> feat(slider): support `mark`

- package.json
Version 12.X.X will have commit errors, so revert back to 11.X.X first
> chore: lint-staged downgraded version

- src/carousel/demos/zhCN/hover.demo.md
docs(carousel): more clear doc
> docs(carousel): more clear doc

- src/input/tests/Input.spec.tsx
> test(input): Update input component test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/src/Slider.tsx
> fix(slider): tooltip tracking timing

- src/log/demos/enUS/index.demo-entry.md
- src/log/demos/zhCN/index.demo-entry.md
> docs(log): improve `trim` props docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/src/Slider.tsx
- src/slider/tests/Slider.spec.ts
> fix(slider): fix fill style

- .github/workflows/node.js.yml
> refactor(ci): use actions/setup-pnpm@2

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/log/src/LogLine.tsx
> fix(log): `trim` prop not being independent when used

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/slider/src/Slider.tsx
optimize performance and fix when processing precision.
> perf(slider): optimize performance when processing precision

- src/upload/demos/enUS/download.demo.md
- src/upload/demos/enUS/index.demo-entry.md
- src/upload/demos/zhCN/download.demo.md
- src/upload/demos/zhCN/index.demo-entry.md
> docs(upload): docs for download

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/scrollbar/src/ScrollBar.tsx
> fix(scrollbar): judement error on mouse up away

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popover/src/Popover.tsx
> fix(popover): onFocus

- src/log/demos/enUS/index.demo-entry.md
- src/log/demos/zhCN/index.demo-entry.md
> docs(log): update trim prop docs

- src/table/tests/Table.spec.ts
> test(table): update test

- src/popover/demos/enUS/trigger.demo.md
> Fix typo in demo: "Focus" label at `focus` trigger

- src/time/tests/Time.spec.ts
- src/timeline/tests/Timeline.spec.ts
> test(timeline): update test

- src/alert/tests/Alert.spec.ts
> test(alert): update test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/element/index.ts
> fix: NEl alias name export

- src/date-picker/demos/enUS/index.demo-entry.md
- src/date-picker/demos/zhCN/index.demo-entry.md
> docs: add month and year docs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/date-picker/src/DatePicker.tsx
- src/locales/common/deDE.ts
- src/locales/common/enUS.ts
- src/locales/common/idID.ts
- src/locales/common/jaJP.ts
- src/locales/common/nbNO.ts
- src/locales/common/ruRU.ts
- src/locales/common/ukUA.ts
- src/locales/common/zhCN.ts
> fix: add yearPlaceholder when type is year

- demo/pages/docs/i18n/enUS/index.md
- src/locales/common/enUS.ts
- src/locales/common/idID.ts
- src/locales/date/idID.ts
> fix(i18n): fix `idID` code problem and `enUS` word spelling

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input/src/Input.tsx
> fix: click clear dont trigger change event

- src/time-picker/demos/zhCN/index.demo-entry.md
> docs(time-picker): update doc

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/src/InputNumber.tsx
> fix(input-number): cursor movement problem (#1759)

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/alert/src/Alert.tsx
> fix(alert): fix `n-alert`'s `header` slot unable to display normally

- src/auto-complete/tests/AutoComplete.spec.ts
> test(auto-complete): update test

- src/badge/tests/Badge.spec.ts
> test(badge): update test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/data-table/src/use-table-data.ts
> fix: onUpdatePageSize does not trigger

- src/button/tests/Button.spec.tsx
> test(button): update test

- src/menu/demos/zhCN/index.demo-entry.md
> 修复文档: menu 组件 错别字修改

- src/image/demos/zhCN/index.demo-entry.md
> docs(image): fix default value of object-fit

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/popselect/demos/enUS/index.demo-entry.md
- src/popselect/demos/enUS/slot.demo.md
- src/popselect/demos/zhCN/index.demo-entry.md
- src/popselect/demos/zhCN/slot.demo.md
- src/popselect/src/Popselect.tsx
- src/popselect/src/PopselectPanel.tsx
> feat: popselect add slots

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/avatar/demos/enUS/index.demo-entry.md
- src/avatar/demos/zhCN/index.demo-entry.md
- src/avatar/src/Avatar.tsx
> fix(avatar): `n-avatar`'s `color` prop will not be recommended, please use `style` prop

- CHANGELOG.zh-CN.md
> docs(changelog): fix changelog problem

- build/loaders/ComponentDemoTemplate.vue
- build/loaders/convert-md-to-demo.js
- build/loaders/convert-vue-to-demo.js
- build/utils/get-demo-by-path.js
- build/utils/tsToJs.js
- build/vite-plugin-demo.js
- demo/utils/ComponentDemo.vue
> chore: optimized ts to js code

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/anchor/src/AnchorAdapter.tsx
- src/anchor/src/styles/index.cssr.ts
let anchor CSS var prefixed with n
> feat(anchor): let CSS var prefixed with n

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/src/utils.ts
- src/input-number/tests/InputNumber.spec.tsx
> fix: input-number cannot input negative decimals

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/scrollbar/src/ScrollBar.tsx
- src/data-table/src/TableParts/Body.tsx
> fix: data-table horizontal scrollbar disappears when max-height not set

- src/input/demos/zhCN/index.demo-entry.md
> docs(Input): fix grammar

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/divider/src/Divider.tsx
- src/divider/src/styles/index.cssr.ts
> feat(divider):divider uses n as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/typography/src/a.tsx
- src/typography/src/blockquote.tsx
- src/typography/src/create-header.ts
- src/typography/src/hr.tsx
- src/typography/src/ol.tsx
- src/typography/src/p.tsx
- src/typography/src/styles/a.cssr.ts
- src/typography/src/styles/blockquote.cssr.ts
- src/typography/src/styles/header.cssr.ts
- src/typography/src/styles/hr.cssr.ts
- src/typography/src/styles/list.cssr.ts
- src/typography/src/styles/p.cssr.ts
- src/typography/src/styles/text.cssr.ts
- src/typography/src/text.tsx
- src/typography/src/ul.tsx
- src/typography/tests/__snapshots__/Typography.spec.ts.snap
> feat(typography): `typography` uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/switch/src/Switch.tsx
- src/switch/src/styles/index.cssr.ts
> feat: switch cannot click when loading status

- src/switch/demos/zhCN/color.demo.md
- vercel.json
Currently naive use a 404 fallback to index.html as a site entry. It works but somehow it's not a good practice, so I vercel rewrites to solve the problem.
> site: vercel rewrites

- package.json
- scripts/md-to-vue.js
- scripts/utils/loader.js
> chore: add md-to-vue script

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/log/src/Log.tsx
- src/log/src/styles/index.cssr.ts
- src/log/tests/Log.spec.tsx
> feat(log): use `n` as CSS vars prefix

- src/spin/src/Spin.tsx
- src/spin/src/styles/index.cssr.ts
- src/spin/tests/__snapshots__/Spin.spec.ts.snap
> feat(spin): uses `n` as CSS vars prefix

- src/statistic/demos/enUS/index.demo-entry.md
- src/statistic/demos/zhCN/index.demo-entry.md
Add `value-style` to `Statistic Props` docs
> Docs: Add missing prop to Statistics

- build/loaders/convert-md-to-demo.js
- build/loaders/convert-vue-to-demo.js
- build/loaders/naive-ui-demo-loader.js
- build/utils/handle-merge-code.js
- demo/utils/ComponentDemo.vue
- src/select/demos/enUS/add-tooltip.demo.md
- src/select/demos/zhCN/add-tooltip.demo.md
> refactor: optimized vite-demo plugin code

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/menu/src/Menu.tsx
- src/menu/src/styles/index.cssr.ts
> feat(menu):`menu` uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/layout/src/Layout.tsx
- src/layout/src/LayoutFooter.tsx
- src/layout/src/LayoutHeader.tsx
- src/layout/src/LayoutSider.tsx
- src/layout/src/styles/layout-footer.cssr.ts
- src/layout/src/styles/layout-header.cssr.ts
- src/layout/src/styles/layout-sider.cssr.ts
- src/layout/src/styles/layout.cssr.ts
- src/layout/tests/__snapshots__/Layout.spec.ts.snap
> feat(layout):`layout` uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/page-header/src/PageHeader.tsx
- src/page-header/src/styles/index.cssr.ts
> feat(page-header): uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/list/src/List.tsx
- src/list/src/styles/index.cssr.ts
> feat(list):`list` uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/image/src/ImagePreview.tsx
- src/image/src/styles/index.cssr.ts
> feat(image): uses n as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/form/src/FormItem.tsx
- src/form/src/styles/form-item.cssr.ts
ref [#1842](https://github.com/TuSimple/naive-ui/issues/1842)
close [#1996](https://github.com/TuSimple/naive-ui/issues/1996)
> feat(form): uses n as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/empty/src/Empty.tsx
- src/empty/src/styles/index.cssr.ts
- src/empty/tests/__snapshots__/Empty.spec.ts.snap
- src/select/tests/Select.spec.tsx
ref [#1842](https://github.com/TuSimple/naive-ui/issues/1842)
close [#1988](https://github.com/TuSimple/naive-ui/issues/1988)
> feat(empty): uses n as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/element/src/Element.ts
> feat(element): uses n as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/_internal/scrollbar/src/ScrollBar.tsx
- src/_internal/scrollbar/src/styles/index.cssr.ts
> feat(internal):`scrollbar` uses `n` as CSS vars prefix

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/element/src/Element.ts
> fix(element): remove n prefix

- src/tree/demos/zhCN/index.demo-entry.md
> docs: update tree docs

- src/upload/demos/enUS/index.demo-entry.md
- src/upload/demos/zhCN/index.demo-entry.md
> docs: complement upload docs

- src/select/tests/Select.spec.tsx
> test(select): update test

- jest.config.js
> workflow: yarn or cnpm mirror source cannot run test(empty) when use pnpm

- src/locales/common/frFR.ts
close #2025  , Thanks for @M1CK431's French translation.
> i18n: update frFR

- src/log/demos/enUS/auto-buttom.demo.md
- src/log/demos/enUS/index.demo-entry.md
- src/log/demos/zhCN/auto-bottom.demo.md
- src/log/demos/zhCN/index.demo-entry.md
> docs(log): add demo for scroll to latest

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/empty/demos/enUS/index.demo-entry.md
- src/empty/demos/zhCN/index.demo-entry.md
- src/empty/src/Empty.tsx
- src/empty/src/styles/index.cssr.ts
- src/empty/tests/Empty.spec.ts
> feat(empty): add show-icon prop

- src/result/demos/enUS/index.demo-entry.md
- src/result/demos/zhCN/index.demo-entry.md
- Status only accepts `string` and not `number`
- Status `400` does not exist
> Docs: Adjust Results prop status types

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/input-number/src/utils.ts
- src/input-number/tests/InputNumber.spec.tsx
> fix: input-number cannot input decimals ending in 0

- src/switch/tests/Switch.spec.tsx
> test(switch): update test

- src/popover/demos/enUS/index.demo-entry.md
- src/popover/demos/zhCN/index.demo-entry.md
- src/popselect/src/Popselect.tsx
> fix: popselect remove arrow prop

- src/tabs/tests/Tabs.spec.tsx
> test(tabs): update test

- src/avatar/tests/Avatar.spec.tsx
> test(avatar): add test case

- src/dynamic-input/demos/enUS/index.demo-entry.md
- src/dynamic-input/demos/zhCN/index.demo-entry.md
> doc: fix dynamic-input api doc

- src/tabs/demos/enUS/index.demo-entry.md
Fix Typo. `TabPane Props` is `Tab Props`
> Docs: Fix Typo

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- demo/utils/EditOnGithubButton.vue
- src/form/src/Form.tsx
- src/form/src/FormItem.tsx
> fix(form): form validate cannot call promise method

- src/color-picker/src/styles/index.cssr.ts
`cursor: crosshair` is better than the default cursor in `color-piker`
> feat(color-picker): use `cursor: crosshair`

- CHANGELOG.zh-CN.md
- src/page-header/index.ts
- src/page-header/src/PageHeader.tsx
> PageHeaderPorps -> PageHeaderProps

- src/tag/tests/Tag.spec.ts
> test(tag): optimization test

- src/data-table/demos/enUS/index.demo-entry.md
- src/data-table/demos/enUS/simple-editable.demo.md
- src/data-table/demos/enUS/switchable-editable.demo.md
- src/data-table/demos/zhCN/index.demo-entry.md
- src/data-table/demos/zhCN/simple-editable.demo.md
- src/data-table/demos/zhCN/switchable-editable.demo.md
> docs(data-table): add simple editable table

- src/thing/tests/Thing.spec.ts
> test(thing): update test

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/message/demos/enUS/index.demo-entry.md
- src/message/demos/enUS/modify-content.demo.vue
- src/message/demos/zhCN/index.demo-entry.md
- src/message/demos/zhCN/modify-content.demo.vue
- src/message/index.ts
- src/message/src/MessageProvider.tsx
> fix: message export MessageType and lack type

- src/radio/src/styles/radio.cssr.ts
optimization icon enable: Mouse moving effect is gesture effect, disable effect is disabled
> fix(radio.cssr.ts): optimize mouse movement style

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- src/carousel/src/Carousel.tsx
> fix(carousel): when single pic should with no dot

- src/_internal/selection/src/styles/index.cssr.ts
> fix: use paddingSingle theme variable instead of hard coded value

- src/message/demos/enUS/index.demo-entry.md
- src/message/demos/zhCN/index.demo-entry.md
> docs: add containerStyle of message

- src/time/tests/Time.spec.ts
> test(time): update test

- src/avatar/demos/zhCN/color.demo.md
> docs(avatar): fix ending symbol

- src/timeline/demos/enUS/index.demo-entry.md
- src/timeline/demos/zhCN/index.demo-entry.md
- src/timeline/tests/Timeline.spec.ts
> test(time-line): add test and fix icon-size prop docs
